### ISSUE TITLE
performance testing

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1075]
Create a testing plan: 
* identify control
* introduce variables

figure out how to execute and track results

this will probably require some instrumentation work.

**Comment by nikkiattea** [comment]
### Why perf test?
Find out what are our bottlenecks, why are they happening, and how can they be addressed. Report benchmarks for releases and commits. Measure scalability.

### Stress/Load
What conditions will make the backend fall over?

### Objective metrics (with and without clustering)
1. How many clients can a single backend handle?
1. How many events per second?
1. How long does it take an event to get through the backend pipeline?
1. What happens when we get an instance with better i/o?
1. How does it scale with more ram/cpu?
1. What happens if we snapshot a running etcd instance?
1. What do etcd’s internal metrics look like while sensu is running?

### Planning
Initial load testing work:
- [ ] Sensu-backend running on a Kubernetes VM
- [ ] Sensu-agent(s) running on a Kubernetes cluster (connected to said backend)
- [ ] Scale up # connections until we break things

**Comment by grepory** [comment]
I'd like us to formalize this a little bit more:

What are the experiments we want to run?
How do we collect the metrics we need to see and what are those metrics?
Break the experiments up into individual tickets, and let's knock them out.

**Comment by grepory** [comment]
Documentation: 

https://docs.google.com/document/d/145e25bCrbtJEi7-QN9YK9koBDd1UxdKrUU8lqsCl6yw/edit

https://docs.google.com/spreadsheets/d/1ktQim5p7kwprrgjZjW9CSJEReACWZVO_xoc6qrnxOE8/edit#gid=0

**Comment by grepory** [comment]
I'm going to close this in favor for stability / performance milestone tickets.
