### ISSUE TITLE
Agent authentication

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1078]
All agents currently authenticate to the backend using the same credentials, and they are granted virtually all permissions, which is not desired.

We need to determine the desired behaviour around agent authentication. Some discussion tracks:
- Should agents across the same environments share the same authentication? (e.g. SSL certificates https://github.com/sensu/sensu-go/issues/203)
- How should agents authenticate against the backend?
- What about an unverified workflow for agents authentication (https://github.com/sensu/sensu-go/issues/201)
- Agents permissions (e.g. https://github.com/sensu/sensu-go/issues/1003)

**Comment by gbolo** [comment]
Hi @jaredledvina, excellent points you made here. I will add some thoughts (about server auth too)

- The agent can further validate the backend endpoint with an SKI (cert pinning). In this case, we can use leverage x509 certificates signed by a standard authority (instead of an internal one) and simply provide the agent the expected cert pin.

- I like the idea of OCSP and CRL status for agent certificates. Maybe we can look at the possibility of utilising a certificate transparency log as an alternative? Also we can use SKI of agent certificates to further authenticate an agent. The benefit of using SKI here is that we can easily revoke a cert without the need for any other infrastructure mentioned above.

- In terms of ciphers, since we write both the backend and agent, there is no need to make them configurable. TLS 1.2 with only PFS ciphers #2700

**Comment by nikkixdev** [comment]
The mTLS agent authentication proposal can be found [here](https://docs.google.com/document/d/1wPuB3it46C-tztvP2ke4dbjNkXSnB9zQKfWDp4J5klY/edit?usp=sharing).

**Comment by portertech** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mTLS Agent authentication](https://trello.com/c/JGhswnA1/1-mtls-agent-authentication)

**Comment by portertech** [comment]
We are proceeding with the proposed mTLS approach linked to above. This will be an Enterprise feature.
