### ISSUE TITLE
"proxy_requests" attribute not supported when importing v1.2 check with sensuctl

### ISSUE THREAD

**Issue by bukiadeniji** [sensu/sensu-go#1205]
"proxy_requests" attribute not supported in creating Proxy checks when importing a v1.2 legacy json check

## Expected Behavior
ability to create and import a v1.2 json check with the following attributes
```
...
...
 "proxy_requests": {
        "entity_attributes": {
              "subscriptions": "eval: value.include?('linux')"
      }
 ...
 ...
```

## Current Behavior
The import fails with error "checks with 'proxy_requests' attribute are not supported at this time"

## Possible Solution
1. "proxy_requests" attribute should be supported so v1.2 checks can be imported
2. sensuctl should contain a flag for "proxy_requests" so proxy checks can be configured by CLI

## Steps to Reproduce (for bugs)
Create check to with the "proxy_requests" attribute 
```
{
  "checks": {
    "check_ping_proxy": {
      "command": "check_ping -H :::address::: -w 5,2% -c 10,5%",
      "subscribers": [
        "round-robin:MON"
      ],
      "interval": 60,
      "proxy_requests": {
        "entity_attributes": {
          "subscriptions": "eval: value.include?('linux')"
        }
      }
    }
  }
}
```
Import with sensuctl
```
$ cat check_ping_proxy.json | sensuctl import --legacy
ERROR   checks with 'proxy_requests' attribute are not supported at this time

==============================
ERROR unable to continue due to errors
```
## Context
Use case: I want an external central agent to do a ping check (or ssh check) to all 500+ (and growing) servers in my network. 
Currently unable to create a proxy requests with attributes that match multiple entities. Alternative is to create 500+ checks for just one parameter - which  is not feasible

## Your Environment
* ```
sensu-backend version
sensu-backend version 2.0.0-nightly#150c23b, build 150c23b72eb7c2be78773294a2da3397bb781cf7, built 2018-03-09T01:43:45+0000
```
* Installation method (packages, binaries, docker etc.): **Packages**
* Operating System and version (e.g. Ubuntu 14.04): **CentOS Linux release 7.4.1708**
* Entities: **500+**

**Comment by majormoses** [comment]
Filters are very much one of the more difficult to figure out how to migrate as go will not have a ruby `eval`.

**Comment by bukiadeniji** [comment]
Thanks @majormoses -  I also get `ERROR   checks with 'proxy_requests' attribute are not supported at this time` with using the following. It seems its failing on the "proxy_request" attribute.

```
      "proxy_requests": {
          "entity_attributes": ["entity.Class == 'proxy'"]
      }
```

**Comment by palourde** [comment]
Hi @bukiadeniji,

As @majormoses stated, the ruby `eval` functionality is no longer supported in Sensu 2 and unfortunately, we had to change the syntax to what we now call the Sensu Query Expressions (SQE), which is essentially based on [govaluate](https://github.com/Knetic/govaluate). 

We are actively working on documentation around this new feature and we will try to provide as much examples as possible to help users convert their `eval` statements to SQE, but I don't think it will be possible to automatically convert them. This is why the `import` command throws an error if your check has the `proxy_requests` attribute configured; it will need to be manually imported.

For reference, it's not possible yet to do something similar to `eval: value.include?('linux')` in SQE, because of this issue: https://github.com/sensu/sensu-go/issues/922. Hopefully we can fix that soon!
