### ISSUE TITLE
Use lowercase sensitive "github.com/sirupsen/logrus"

### ISSUE THREAD

**Issue by nikkiattea** [sensu/sensu-go#1261]
Our vendor dependency tree references "github.com/Sirupsen/logrus" which was changed to "github.com/sirupsen/logrus" in https://github.com/sirupsen/logrus/pull/384. This causes an issue with updating other vendor packages which are dependent on logrus. We should find a way to clean this up in order to update certain packages to more recent versions (ex. github.com/atlassian/gostatsd).

```
Solving failure: No versions of github.com/atlassian/gostatsd met constraints:
	5.4.0: Could not introduce github.com/atlassian/gostatsd@5.4.0 due to a case-only variation: it depends on "github.com/sirupsen/logrus", but "github.com/Sirupsen/logrus" was already established as the case variant for that project root by the following other dependers:
	(root)
	github.com/docker/docker@v1.13.1
	github.com/tmc/grpc-websocket-proxy@timestamp_stdtime_example
```

**Comment by nikkiattea** [comment]
Any objections to upgrading our docker dependency version to https://github.com/moby/moby/commit/cbde00b44273a584bed2ee3513db68924b4a6dba ? Our current docker version (1.13.1) uses "github.com/Sirupsen/logrus" as well.

**Comment by cyphus** [comment]
When I looked into this last week, I found that all our direct dependencies that import capital-S Sirupsen have newer versions available that use the lowercase-s version. Upgrading those dependencies should be pretty straightforward, but I recommend going through the changelogs and checking for anything that would affect our project as a matter of due diligence.

Hopefully everyone here is using a case-sensitive filesystem, otherwise they may have to delete the Sirupsen installation directory manually before installing the lowercase-s version.

**Comment by cyphus** [comment]
Installing or upgrading to High Sierra will automatically convert the root partition to APFS on supported hardware, and I thought that APFS was case sensitive, which would mean that only people who either haven't upgraded, opted out of partition conversion, or are on unsupported hardware were affected.

But alas, APFS is case insensitive by default. We may end up getting bit by this.

**Comment by echlebek** [comment]
I tried running a case-insensitive OS X install for a while and it broke several things in userland. It was actually really annoying. So it doesn't surprise me that the default for APFS is case-insensitive.
