### ISSUE TITLE
Agent panics if statsd flush interval is set to default value

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1345]
In the benchmark test, a new agent is created with a default statsd config. Since the default int value is 0, a value of 0 is passed to statsd here: https://github.com/sensu/sensu-go/blob/master/agent/statsd_server.go#L30

We should check that this is non-zero when starting up the server, and set it to a reasonable default if it is.

**Comment by nikkiattea** [comment]
Whoops oh no! The default statsd config should have a flush interval of 10. Can you show me where in the benchmark test you're configuring the agent?

**Comment by echlebek** [comment]
https://github.com/sensu/sensu-go/blob/master/benchmark/cmd/main.go#L34 is where the agent is configured.

For now I've just set the config to be disabled. Not sure where the default should go.

**Comment by nikkiattea** [comment]
So `NewConfig()` creates an _empty_ agent config, but `FixtureConfig()` will create an agent config with the default values. I suppose you could use either in testing and assign values as you see fit. But you did expose a bug where a user could enter `--statsd-flush-interval 0` and crash the agent. Let me submit a patch for this real quick 😉

**Comment by echlebek** [comment]
Well, NewConfig() should at least create a config that won't lead to a panic. Maybe the default should be for statsd to be disabled. (Have an `enabled bool` field instead of `disabled bool`)

**Comment by nikkiattea** [comment]
I think by design we wanted statsd to be enabled by default. For example, our tcp/udp listeners behave the same and are enabled by default. I'm also all ears if there is other reason to disable it by default. We could disable statsd in `NewConfig()` but that defeats the purpose of `// NewConfig provides a new empty Config object`. I'm wondering if we should invoke `FixtureConfig()` [instead of NewConfig() here](https://github.com/sensu/sensu-go/blob/master/benchmark/cmd/main.go#L34-L51) since much of the work setting the defaults is already done?

**Comment by echlebek** [comment]
It's fine to enable statsd by default, but the NewConfig should make that possible - right now it lacks enough information to start up. (Missing host to bind to, possibly other things.)

`FixtureConfig()` is probably not the right thing here - that should only be used in tests.
