### ISSUE TITLE
Remove omitempty from json tag for boolean attributes

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#1497]
Related to https://github.com/sensu/sensu-go/issues/1341.

Boolean values configured to `false` are not displayed in JSON, which is misleading.

**Comment by nikkiki** [comment]
Boolean values configured to `false` do not display in JSON because the `omitempty` tag is hardcoded in auto-generated `.pb.go` files (see [generator.go](https://github.com/golang/protobuf/blob/1687f003bf0280bd6182a5a1c7241856b269a6c0/protoc-gen-go/generator/generator.go#L1788)).

This [blog post](https://medium.com/@nevio/golang-dealing-with-protocol-buffer-omitempty-and-boolean-json-responses-ae1ba5f4e9c3) suggests the following hack over manually stripping `omitempty` from boolean values in the files.
```
ls *.pb.go | xargs -n1 -IX bash -c "sed -e '/bool/ s/,omitempty//' X > X.tmp && mv X{.tmp,}"
```

At the moment, I'm trying to implement the hack with `go generate` so its done each time we generate protobufs.

**Comment by nikkiki** [comment]
Upon further investigation, a much simpler solution would be setting the jsontag for all bool values manually in each proto `[(gogoproto.jsontag) = "expire_on_resolve"]`. Doing so does not append `omitempty` in the pb.
