### ISSUE TITLE
Creating a staging environment for Sensu 2.x

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1586]
Create a general staging environment for Sensu 2.x. While we would like to eventually use chef or puppet here, something involving docker on AWS is fine for now.

Create a Sensu backend and several agents (at least 3) that exercise the most salient features of the system.

* A combination of static and ephemeral agents with a small variety of subscriptions.
* Check execution with interval, cron and round-robin scheduling.
* Proxy checks.
* Assets.
* Hooks for things that support them.
* Filters, mutators and handlers.
* Metrics via statsd.
* The dashboard.
* RBAC - create different environments and organizations and demonstrate that things are contained.
* A handler extension running in a separate process that handles some of the events generated.

Developers should be able to log into the dashboard and get an idea if things are working normally after a deployment.

Deployment can be manual to start, but we should have a good strategy for automating this as soon as possible.

The deliverable should be a running staging environment, and a script that creates all of the resources mentioned above, using sensuctl.

Parent of https://github.com/sensu/sensu-go/issues/1669
Parent of https://github.com/sensu/sensu-go/issues/1670
Parent of https://github.com/sensu/sensu-go/issues/1671

**Comment by echlebek** [comment]
If desired, break this ticket into multiple smaller issues, and divide them up once a basic environment has been provisioned.

**Comment by nikkiki** [comment]
Let's stick to manual testing in this staging env for now..

**Comment by palourde** [comment]
Few things I noticed, not sure if they are out of scope though.

- Instructions to access the dashboard are missing.
- We don't have a _proper_ asset configured, therefore the check `check-with-asset` is returning an error because of a checksum mismatch.
- No check using round-robin mechanism.

Finally, this is definitely out of scope but are we planning on writing a QA checklist, so we know exactly what to look for when testing this environment?

**Comment by nikkiki** [comment]
@palourde Thanks for the feedback!
1. Do you mean the Sensu Dashboard or the AWS EC2 Dashboard?
2. This is true, I mostly used the same resources used in the e2e tests. But it would be beneficial to have a valid asset. @jspaleta mentioned we could use a popular community plugin to test. Could either of you point me to one that is widely used?
3. Wow, good catch. `passing-round-robin` check has `round_robin` set to false 🤦‍♀️.

**Comment by palourde** [comment]
1. Ah yes sorry, the Sensu Dashboard!
2. By experience, I would say one of the most popular plugin must be [check-http.sh](https://github.com/sensu-plugins/sensu-plugins-http/blob/master/bin/check-http.rb), however it would require Ruby, which might complicate things. Otherwise, one of the only bash plugin I know of is [check-cpu.sh](https://github.com/sensu-plugins/sensu-plugins-cpu-checks/blob/master/bin/check-cpu.sh).
3. 😆

**Comment by nikkiki** [comment]
@palourde Made those revisions to the staging doc and resources! Thanks again!

**Comment by palourde** [comment]
![](https://i.imgur.com/uz7pc1F.gif)

**Comment by jspaleta** [comment]
@nikkiki 
FYI, for my own work..
I was going to start using the list from bestgems moving forward as best effort to prioritize plugin by popularity.
http://bestgems.org/search?q=sensu-plugin
