### ISSUE TITLE
Incorporate etcd cluster health information in the sensu health endpoint

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1716]
Apid should request cluster health information from etcd and use that information to inform the sensu health check.

Investigate the detailed health information provided by etcd, and decided whether to incorporate this information in sensu's health report.

Note that the API for health information has changed dramatically from the etcd v2 api to v3.

**Comment by grepory** [comment]
Our high level goal with this endpoint (and displaying the information in the sensuctl output), is to provide enough information to determine the health of both the cluster and a single node. If a node is a member of a minority partition, it should be considered unhealthy--so that a load balancer knows not to route client connections to that node as its performance is degraded.

The v3 etcdctl endpoint health command queries each of the advertised peer URLs and attempts to get the "health" key. The endpoint is considered healthy if there's a response and no error. See https://github.com/coreos/etcd/blob/master/etcdctl/ctlv3/command/ep_command.go#L87 for details on how etcdctl does this.

The rationale behind this is that GETs to etcd are consistent--meaning they require consensus--meaning it requires a quorum. A minority partition or an unavailable/unhealthy cluster member should return an error from a GET.

**Comment by mercul3s** [comment]
It looks like we already have an implementation of this in the API - /info and /health routes exists here: https://github.com/sensu/sensu-go/blob/master/backend/apid/routers/status.go#L32
mapped to a Healthy() function in etcd: https://github.com/sensu/sensu-go/blob/master/backend/etcd/etcd.go#L271
This implementation is a bit different than what is specced in this ticket (uses the NewMaintenance func) and is untested and undocumented, so I'm going to start by writing some tests to figure out if it does what we want. I'll modify if it doesn't, because I don't think we're currently using this route.
