### ISSUE TITLE
Investigate cluster failure mode: partitions

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1723]
Use the staging environment to create partitions between nodes in the sensu cluster. Investigate what happens to the cluster what partitions are created.

- What happens on the minority partition?
- What happens when a partition is healed?
- What happens to backend components that require etcd besides the store?
    - queues
- what happens if queue members are connected to a minority?
    - monitors/ttls
- what happens when an agent is connected to a minority?
- How do agents behave during a partition?
- How do we internally monitor and react to etcd errors?

When problems are encountered, file issues and add them to the clustering epic. Document any findings in this issue.

**Comment by cyphus** [comment]
What happens to backend(s) on the minority partition?
- no etcd reads or writes go through on the backend (timeouts every time)
- etcd repeatedly attempts to connect to the other cluster members
- sensuctl cannot make any requests against the minority partition backend (because getting the authorization token times out)
- random CPU spikes between 10 and 35%

What happens if queue members are connected to a minority?
- any connected agents remain connected but no longer execute checks (as there are no check requests sent from the backend) and agent keepalives continue to be sent but are not processed by the backend.
- suggestion: if the backend kills all agent connections when etcd encounters a failure mode, the agents will reconnect to the next backend (if configured) and can continue sending keepalives and executing checks

What happens when a partition is healed?
- Minority member rejoins etcd cluster
- Reads/writes start flowing again
- Check execution and keepalives resume with connected agents
- I'm pleasantly surprised with these results

**Comment by echlebek** [comment]
> I'm pleasantly surprised with these results

Requirements filled!

**Comment by cyphus** [comment]
How do we internally monitor and react to etcd errors?
- See  #1724 

What happens to backend components that require etcd besides the store (queue)?
- As of right now, the queue is only used for adhoc checks, and adhoc checks cannot be executed against a sensu-backend instance in the minority partition (because no sensuctl commands can be exeucted)
- Adhoc checks can still be queued for execution against sensu-backend instances in the majority partition, but if the agent is not connected to one of those backends, it stays in the queue until the partition is healed.

As a side note, etcd doesn't accept client connections when a quorum is not available, so the logs get filled with grpc warnings:

```
WARNING: 2018/08/13 22:48:47 Failed to dial 127.0.0.1:36685: grpc: the connection is closing; please retry.
```

These warnings stop once the partition is healed.

At this point I've covered the full surface area of cluster partitioning based failure modes. Closing this.
