### ISSUE TITLE
Testing support tools in tools/bin aren't found in CircleCI

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#1797]
Master build is failing on CircleCI because of a unit test. After some investigation, it appears that the supporting tools for check execution testing are no longer being compiled. Or at least, some of them aren't.

See the build log here: https://circleci.com/gh/sensu/sensu-go/328

Using delve, inspected the event under test and found in the output:

```
Output: "sh: 1: ../bin/tools/true: not found\n",
		State: "",
		Status: 127,
```

Also

```
		Output: "sh: 1: ../bin/tools/cat: not found\n",
		State: "",
		Status: 127,
```

So I'm assuming that none of bin/tools/* are there.

Confirmed:

```
circleci@2d1ffeeb4dc7:/go/src/github.com/sensu/sensu-go$ ls bin/tools
ls: cannot access 'bin/tools': No such file or directory
```

## Expected Behavior
Those binaries should be compiled, and the tests should pass.

## Current Behavior
The binaries aren't compiled, and the tests fail.

## Possible Solution
Compile them? :)

**Comment by preed** [comment]
This is due to 1a08b8065:

@amdprophet said the "[`build_tools` target] builds tools (cat, false, etc.) cross platform for e2e tests. But we're phasing out e2e tests so we can scrap them."

It's easy to re-add the target, but for clarification: we actually _do_ need them?

(Also, my understanding is these are required to build on Windows? If we're on non-Windows, couldn't we just use the platform native tools? Or is there a GNU/BSD cross-platform issue as well?)

**Comment by amdprophet** [comment]
Using the platform native tools will require adding platform-specific testing as the Windows tools act a bit differently than the Linux tools.

We've made use of a trick that the Go project uses that may be a more appropriate option for this case. It involves tests that require shellout to run another Go test which allows us to control the output. See https://github.com/sensu/sensu-go/blob/master/backend/pipelined/handle_test.go#L42-L55 for an example.
