### ISSUE TITLE
Keep agents informed about backend URLs

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1878]
In a sensu cluster, backends can come and go. When this happens, agents should be apprised of the URLs that are joining and leaving the cluster.

Create a mechanism to keep agents up to date about changes to cluster membership, so that they can gracefully reconnect to new cluster members.

**Comment by grepory** [comment]
Cluster members are statically configured via command-line arguments or configuration files. Those are immutable to the agent. When the agent process restarts, it will lose any cluster member information made available to it.

This problem is better solved by configuration management or a load balancer.
