### ISSUE TITLE
Display the current backend URL agents are connected to in the entity list

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#1879]
Now that we have clustered sensu, we need a way to show operators which backends agents have established their session on.

Add a field called "backend_url" to the entity list, and have it display the URL of the backend the agent is connected to. If the entity is a proxy entity, don't display anything.

**Comment by grepory** [comment]
This is considerably more bookkeeping than you may expect.

The backend URL cannot simply be supplied by the agent in the keepalive, because there may be a load balancer between the agent and the backend. So, the backend has to be responsible for mutating the entity provided in the keepalive with the backend's hostname (assuming the OS is correctly configured and the kernel can correctly report its own hostname). This data has to be persisted and replicated across the cluster so that all backends can report connections for all agents.

Now that we're storing connection state details in etcd, we have to maintain them.

During a network partition, we may lose a backend and all of its connected agents. The cluster cannot know that there is a network partition, and thus only sees the disappearance of a portion of agents and a backend node.

The majority cluster (separated from the partitioned entities), are now reporting that all of the partitioned agents are connected to a cluster node that is no longer present. This is an untrustworthy view of the world--as only the missing backend node truly knows whether or not an agent is connected to it, but we're unable to communicate with that node. Given that the node and all connected agents could be gone for a non-trivial amount of time (let's say this particular network partition lasts for two hours), we probably don't want to report that agents are connected to that node.

If that's the case, then any time there is a cluster partition, we have detect which nodes are in the minority partition, find all entities associated with those nodes, and remove the backend URL from all of those entities. If, while doing this, the minority partition reconnects, then we'll be in the middle of purging entity connection state as new keepalive data comes in and updates it. So there may be some minutes where the data is inaccurate--during a period of time where I would expect this data to be actually important (when agents are connecting/reconnecting/rejoining the sensu swarm).

What about when an agent naturally disconnects?

When an agent naturally disconnects, after a timeout period the session could remove the connection state for that entity. There may be a period of time where there is a live session on backend A for an entity, but the entity has connected to backend B. Backend A may remove the connection state making it look like the entity is disconnected until backend B re-updates the connection state. This means, of course, that connection state has to be constantly updated during the course of an agent's session on a backend.

I am 100% certain that there are cases I have not considered, and that we will not consider if we implement this. This leads me to believe that storing connection state in etcd is probably not the best route to determine where a given agent is connected.

As I and @oferrigni mentioned in Slack, it's much better to inspect the agent in order to determine where it is connected. Minimally, this can be accomplished with `netstat -t | grep 8081` (or whatever the agent web socket port is for your installation). The agent can also log which backend it's connected to. We could also have a backend report its hostname in headers so that a load balancer can't obscure the backend's hostname and the agent can still log which backend it's connected to.

**Comment by oferrigni** [comment]
Closing this as we have this info in the agent logs already.
