### ISSUE TITLE
sensuctl entity create --interactive does not prompt for ID

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#1961]
When creating an Entity with `sensuctl` in interactive mode, it does not prompt you for an Entity ID when it hasn't been provided as a CLI argument. It will error out after prompting for all other values.

## Expected Behavior
If you do not provide an Entity ID as an argument it will prompt for one (or error out immediately).

## Current Behavior
It does not prompt you for an Entity ID when it hasn't been provided as a CLI argument. It will error out after prompting for all other values (annoying).

**Comment by roganartu** [comment]
I hit this today. Example output:
```
 sensuctl entity create --interactive 
? Entity Class: proxy
? Subscriptions: switches
? Namespace: default
Error: entity name must not be empty
```
At the very least, the error should happen immediately. Ideally it should prompt for entity name as well though.

**Comment by nikkixdev** [comment]
Ah yes I can see how this would be annoying. Good news is, it's relatively simple to fix! The [interactive entity questionnaire](https://github.com/sensu/sensu-go/blob/master/cli/commands/entity/interactive.go#L33) should definitely contain a field for the name in the event the name is not supplied through `args[0]`, or [the error should be caught sooner](https://github.com/sensu/sensu-go/blob/master/cli/commands/entity/create.go#L29). Happy to see your implementation @roganartu otherwise I can make sure this gets queued up soon!

**Comment by roganartu** [comment]
This isn't a priority for me so I'm happy to let you guys handle it, thanks
