### ISSUE TITLE
Add a command to sensuctl to expose Sensu version

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#2040]
Requires #1739 

### Todo
- [ ] Determine the name of the new command
- [ ] Expose the information provided by the endpoint in #1739

**Comment by grepory** [comment]
Regardless of #2105, we can use our etcd client to get the version of the etcd cluster we're connected to (embedded or otherwise). The etcd [client](https://godoc.org/github.com/etcd-io/etcd/client) (not the v3 client), exposes a `GetVersion` call.

We have #1739 to expose a `/info` endpoint. We should expose Sensu version, sensu-backend build information, and etcd version as part of this endpoint.

**Comment by annaplotkin** [comment]
We should review existing endpoints and make the right choice about where we expose this info.

**Comment by palourde** [comment]
The version is now exposed via the API (via https://github.com/sensu/sensu-go/pull/2970), we should definitely tackle this issue!
