### ISSUE TITLE
Clarify 'custom-attributes' and 'extended_attributes'

### ISSUE THREAD

**Issue by absolutejam** [sensu/sensu-go#2051]
Currently, the template agent.yml and CLI reference `custom-attributes:` but the docs reference `extended_attributes`. Also, neither one *clearly* states that they require a serialized JSON object as a string value.

## Expected Behavior
Single config value that is consistent across all documentation and config locations.

## Current Behavior
Two different parameters/config values.

## Possible Solution
Standardise on a single config value.

## Steps to Reproduce (for bugs)
`sensu start --help` vs. `/etc/sensu/agent.yml.example` vs `https://docs.sensu.io/sensu-core/2.0/reference/entities/#how-do-entities-work`

## Your Environment
Windows - `sensu-agent version 2.0.0-beta.4-4#a05ad41, build a05ad411199077286f49c06629eed4823331176c, built 2018-08-16T21:12:56+0000`

And while I have your attention, can you also please see #2007 as I'm still lost as to configure them!

Cheers.

**Comment by annaplotkin** [comment]
Nikki to verify that this is a docs issue.

**Comment by nikkiki** [comment]
@annaplotkin Although [custom attributes and extended attributes are the same](https://github.com/sensu/sensu-go/issues/2007#issuecomment-420424163), we seem to be referring to them inconsistently in both the docs and at the source level. I think the best solution to avoid confusion would be to standardize this. I believe extended attributes is more widely used, but standardizing either term would constitute a breaking change. Otherwise, it's just a docs issue (I'm not sure how expensive the overall confusion is).

**Comment by annaplotkin** [comment]
@nikkiki Thanks for digging into this! 

@grepory @amdprophet @cyphus @oferrigni @nikkiki - My preference here is to standardize on one term. Totally get that it would be a breaking change but I feel we need consistency. My vote would be to standardize and use extended_attributes. What do you all think?

**Comment by grepory** [comment]
There is existing documentation that uses the language "custom attributes".

https://docs.sensu.io/sensu-core/1.5/reference/clients/#custom-attributes

**Comment by grepory** [comment]
Or is that what you're referring to when you say "breaking change"?

I prefer extended attributes as well.

**Comment by nikkiki** [comment]
@annaplotkin +1 for extended attributes

@grepory we'd have to change the agent flag from `--custom-attributes`

**Comment by annaplotkin** [comment]
Awesome, I think we should standardize on the extended_attributes and do the following:

1. Update agent.yml to no longer reference custom attributes and instead reference extended attributes and state that they require a serialized JSON object as a string value.
2. Update CLI reference to no longer reference custom attributes and instead reference extended attributes and state that they require a serialized JSON object as a string value.
3. Update docs to state that they extended_attributes require a serialized JSON object as a string value.

@grepory @nikkiki Does that look right to you all?

**Comment by grepory** [comment]
Right, it is also a breaking change from 1.x in that they are already called custom attributes in 1.x.

**Comment by grepory** [comment]
This affects more than just the agent. It also affects any entities created via the API, checks, handlers, mutators, etc. to have extended attributes.

**Comment by nikkiki** [comment]
@annaplotkin I can certainly do 1 and 2. I believe 3 was addressed in https://github.com/sensu/sensu-docs/pull/691/files but if you want me to elaborate further in the docs I can.

@grepory Could you elaborate? I'm not understanding how the name change impacts that.

**Comment by grepory** [comment]
Right now, custom attributes are submitted via the API as if they are attributes on an object. E.g.

```
POST /entities
{
  "Id": "my-entity-id",
  "my-custom-attribute": "my-value"
}
```

If you consider the configuration file as an "API endpoint", then we now have two ways to submit custom attributes for entities where there is effectively an "custom_attributes" field that takes serialized JSON.

What I'm suggesting is that for all objects that have extended/custom attributes, they specify those attributes via a field that contains serialized JSON.

**Comment by nikkiki** [comment]
@grepory okay, I think I see what you're saying. The configuration file or command line arg allows a user to specify extended attributes for an entity at start up. `/entities` allows a user to specify extended attributes for a new or existing entity at _any_ point. You don't wish to restrain the ability to one of these methods, correct?

Or, are you more concerned with the differing formats that a user can specify the extended attributes?
```
POST /entities
{
    "id": "agent-name",
    "team": "ops"
}
```
vs.
```
$ sensu-agent start --extended-attributes '{"team": "ops"}'
```
so by `they specify those attributes via a field that contains serialized JSON` do you mean you would rather have something like this where the attributes are defined in a single field?
```
POST /entities
{
    "id": "agent-name",
    "extended-attributes":  {"team": "ops"}
}
```

Sorry if I'm totally off here! But isn't the first example here how custom attributes are intended to be, but due to go nuances (i.e. the reason for the dynamic package), we had to accept json serialized objects as single fields? Also I'm totally free to hop on a call to clarify anything of the confusing stuff I probably said!

**Comment by nikkiki** [comment]
Filed https://github.com/sensu/sensu-go/issues/2079 to address the single experience issue Greg has described. I think it's reasonable to address the 3 points Anna summarized above for this ticket.
