### ISSUE TITLE
Proxy checks are not immediately issued on creation

### ISSUE THREAD

**Issue by mercul3s** [sensu/sensu-go#2053]
## Expected Behavior
A new proxy check should be run as soon as it is created, just as non-proxy (agent) checks are immediately run.

## Current Behavior
Newly created proxy checks aren't run immediately - they appear to run after a delay that is probably the interval time. 

## Possible Solution

I dug through schedulerd a bit, and I did notice that proxy checks can have a splay setting - this is not explicitly set in the proxy check config from what I can tell, and I don't see it in the config when I do sensuctl check info <checkname> --format=json. Is it possible that the splay setting is defaulting to true and we're setting splay on every proxy check request?

## Steps to Reproduce (for bugs)

1. Create a standard check 
2. Observe event creation with `sensuctl event list` (happens almost immediately)
3. Create a proxy check
4. `sensuctl event list` until the event eventually shows up

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by nikkiki** [comment]
Okay, it looks like a couple things are happening here. To address some of your questions first, yes all checks _can_ contain a `ProxyRequests` field which defines `Splay` and `SplayCoverage`. Since these fields are not displayed in the check config in json format, it means `check.ProxyRequests == nil`  (see [omitempty](https://github.com/sensu/sensu-go/blob/273d3bb732fb084c92172297888c155c429bf92c/types/check.pb.go#L217)). Additionally, proxy checks will only be splayed if `check.ProxyRequests != nil`, otherwise the check is executed like a normal check: https://github.com/sensu/sensu-go/blob/136a156dc447ac759891533dc6f4bd6b4f910336/backend/schedulerd/executor.go#L287-L303

I have verified that the splay defaults to false as expected, and therefore both the regular and proxy check are executed immediately when the request is received. When trying to reproduce the behavior you're describing, I'm actually seeing the proxy check executing slightly before the agent check.

@mercul3s can you attach the check configs you were using so I can verify the same on my end?

**Comment by mercul3s** [comment]
@nikkiki here's the check config:
```
{
  "check_hooks": null,
  "command": "curl -fs https://account.sensu.io",
  "env_vars": null,
  "environment": "default",
  "handlers": [
    "account-manager-slack"
  ],
  "high_flap_threshold": 0,
  "interval": 300,
  "low_flap_threshold": 0,
  "name": "account-manager-login",
  "organization": "default",
  "output_metric_format": "",
  "output_metric_handlers": null,
  "proxy_entity_id": "account-manager",
  "publish": true,
  "round_robin": false,
  "runtime_assets": null,
  "stdin": false,
  "subdue": null,
  "subscriptions": [
    "account-manager"
  ],
  "timeout": 0,
  "ttl": 0,
  "executed": 0,
  "history": null,
  "issued": 0,
  "last_ok": 0,
  "occurrences": 0,
  "occurrences_watermark": 0,
  "status": 0,
  "total_state_change": 0
}
```
When I was testing this, I didn't end up looking through logs to see the check execution time, rather noticed that the event was not getting created for several minutes. I would expect if a check is executed on creation that it would create an event shortly after.

**Comment by mercul3s** [comment]
@nikkiki the config should be the same with the exception of proxy_entity_id. Since I didn't have debug logging turned on in the account manager sensu instance when I was debugging this, I went ahead and spun up a staging instance to test this and dug through the logs:
```
$ journalctl -u sensu-backend.service | grep 'test-proxy-check'
Sep 20 00:30:01 ip-10-0-1-86 sensu-backend[3856]: {"component":"schedulerd","env":"default","level":"info","msg":"starting new interval scheduler","name":"test-proxy-check","org":"default","time":"2018-09-20T00:30:01Z"}
Sep 20 00:30:01 ip-10-0-1-86 sensu-backend[3856]: {"component":"apid","duration":"8.007ms","level":"info","method":"PUT","msg":"request completed","path":"/checks/test-proxy-check","size":453,"status":200,"time":"2018-09-20T00:30:01Z"}
Sep 20 00:31:55 ip-10-0-1-86 sensu-backend[3856]: {"component":"schedulerd","env":"default","level":"debug","msg":"check is not subdued","name":"test-proxy-check","org":"default","time":"2018-09-20T00:31:55Z"}
Sep 20 00:31:55 ip-10-0-1-86 sensu-backend[3856]: {"check":"test-proxy-check","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-09-20T00:31:55Z","topic":"sensu:check:default:default:account-manager"}
```
From the timestamps, the check creation time and the time the check request is sent are around 2 minutes apart.

**Comment by nikkiki** [comment]
@mercul3s We, my friend, have discovered not a bug, but a FEATURE 😂🤦‍♀️ 

Regardless of being an agent or proxy check, when a check's interval timer _first_ starts, we calculate an [initial offset](https://github.com/sensu/sensu-go/blob/136a156dc447ac759891533dc6f4bd6b4f910336/backend/schedulerd/check_timer.go#L80-L85), to splay the checks _first_ execution and distribute the load. For example, if I created 100 interval checks, I wouldn't want them all to be scheduled immediately and at the exact same time, because that would cause a large concurrent load on the backend's schedulerd and the agent's execution which would be executing 100 checks in the same second.

So in the example below, using the config you provided, the initial offset is 187 seconds (I added a debug log statement in there). If you take the new interval start time `11:19:11` and add `187` seconds, you get `11:22:18` which is when the first check request is issued. All subsequent check requests are issued at the `300` second interval.
```
{"component":"apid","duration":"2.291ms","level":"info","method":"PUT","msg":"request completed","path":"/checks/account-manager-login","size":494,"status":200,"time":"2018-09-20T11:19:11-07:00"}
{"component":"schedulerd","env":"default","level":"info","msg":"starting new interval scheduler","name":"account-manager-login","org":"default","time":"2018-09-20T11:19:11-07:00"}
{"component":"schedulerd","level":"debug","msg":"initial offset for interval timer (in seconds)","offset":187,"time":"2018-09-20T11:19:11-07:00"}
{"component":"schedulerd","env":"default","level":"debug","msg":"check is not subdued","name":"account-manager-login","org":"default","time":"2018-09-20T11:22:18-07:00"}
{"check":"account-manager-login","component":"schedulerd","level":"debug","msg":"sending check request","time":"2018-09-20T11:22:18-07:00","topic":"sensu:check:default:default:account-manager"}
```

I still to this day get confused about the splay we define in proxy checks, and the splay of an interval timer. But I think the debug log message will be helpful in the future, so I'll definitely merge that!

**Comment by mercul3s** [comment]
Womp womp! I was totally unaware of this behavior but it makes total sense. I think that might be useful to make a note about check splay in the documentation so the behavior is clear to users, and also because it's a nice story about performance.
