### ISSUE TITLE
Store the backend as an entity

### ISSUE THREAD

**Issue by nikkictl** [sensu/sensu-go#2184]
Similar to the 1.x server registry, sensu-go should store entity information pertaining to backends. https://github.com/sensu/sensu-go/pull/2182 creates functions to collect system information and create a backend entity, but most other entity fields are irrelevant to the backend. Backend entities can be contained in the existing entity store. Like agent entities, they should not be able to be updated by the API (https://github.com/sensu/sensu-go/issues/2183).

**Comment by nikkixdev** [comment]
This concept came up again in discussions over https://github.com/sensu/sensu-go/issues/3695 asset templating. The entity used to substitute tokens in backend assets (ex. handlers/mutators) is the backend entity, and since that information is not yet stored, an operator must rely on the logs to retrieve backend entity information.

**Comment by calebhailey** [comment]
I like the idea of a new default `sensu-system` namespace with an entity per sensu-backend cluster member. Should the backends also emit keepalive events for themselves?

**Comment by nikkixdev** [comment]
@calebhailey Introducing a built in namespace this late in 5.x could potentially cause a collision with an operators existing namespace, perhaps the notion of a `sensu-system` namespace is better suited for 6.x discussions?

Diving into the backend keepalive idea, I think there would be a way to make that work but would definitely be outside the scope of this ticket. While `cluster health` also indicates when a cluster member is unhealthy, implementing keepalives for backends would give operators access to the event pipeline for unhealthy backends. I suppose this could already be achieved with a check to `sensuctl cluster health` though. It is important to note that backend keepalives would not have been possible in the backend leader architecture from 1.x, but is possible now with the etcd leases we use to consider agent liveness. Again, probably out of scope and worthy of a feature request!

I'm actually tempted to tag this issue with `1.x parity` due to the fact that sensu classic did have a server registry that accomplished a very similar thing.

**Comment by portertech** [comment]
We need to formalize this with a proposal document and review it.
