### ISSUE TITLE
Consistent payload between the agent sockets

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2225]
## Expected Behavior
I expect to be able to send the same payload between the HTTP, TCP and UDP sockets.

## Current Behavior
The HTTP socket requires a different payload from the UDP/TCP ones. E.g.

```
# TCP
echo '{"name": "app_01", "output": "could not connect to mysql", "status": 1}' | nc localhost 3030

# HTTP
curl -s -i -X POST -H 'Content-Type: application/json' \
-d '{"check": {"name": "app_01", "output": "could not connect to mysql", "status": 1}}' \
http://127.0.0.1:3031/events
```

## Possible Solution
Decide to either require a full event object or just a check result. The full object is probably required for proxy entities.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Related to https://github.com/sensu/sensu-docs/pull/824.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by calebhailey** [comment]
Sometime after this issue was created the decision was made to deprecate the Agent TCP/UDP socket, which is accurately captured in the [Sensu Agent reference documentation](https://docs.sensu.io/sensu-go/latest/reference/agent/#create-monitoring-events-using-the-agent-tcp-and-udp-sockets). 

The TCP/UDP socket will accept Sensu 1.x "check results" until it is removed. The Agent HTTP API accepts Sensu Go Events.
