### ISSUE TITLE
events API endpoint does not handle keepalive events

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#2288]
When a well-formed keepalive is received via the events API, the backend does not treat it as a keepalive event. The event is stored, but does not pass through the keepalive handler in keepalived. This precludes the possibility of an event producer that only utilizes the HTTP API from using the (hidden, but discoverable) keepalive feature. Given the future possibility of agents submitting events to the API instead of a special event handler in their "session," this is probably worth investigating and resolving.

**Comment by calebhailey** [comment]
@palourde I'm curious to learn why we closed this. Ever since the events API improvements we shipped in 5.18, I've been thinking about this exact thing (though I didn't realize this issue existed). The behavior described here is how Sensu Core worked, so this could be treated as a "feature parity" issue. 

My thought has been: what is the difference between a "keepalive event" produced by an agent, and an event named "keepalive" published to the Events API? Some interesting (and valuable) solutions become possible if there wasn't a difference.

Example: it would become trivial to implement keepalive monitoring for unsupported platforms (e.g. Solaris) with a simple cron job. 

I suspect the counter argument here is that users could achieve the same result by publishing "heartbeat" events (or any other similar name) and configuring a check TTL. But that prompts me to ask the question: what's the difference between our keepalive watcher system and our TTL watcher system?

**Comment by calebhailey** [comment]
Oh, nevermind: it looks like this was closed because we fixed it in https://github.com/sensu/sensu-go/pull/3652 

Still curious, for my own edification, to understand the difference between keepalive watchers and check TTL watchers (if any?)... but that's a lower priority / discussion for another day. 

🎉

**Comment by palourde** [comment]
@calebhailey Long story short, keepalives and events results are splitted into two different Go channels (queues essentially), therefore they do not exactly go through the same pipeline. The watchers are essentially the same, it's probably just a question of replicating what we had in Sensu Classic with RabbitMQ.

**Comment by calebhailey** [comment]
OK. That helps. Thanks!
