### ISSUE TITLE
Systemd vs sensu-agent start paths are different

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2317]
In testing out the [monitoring external resources guide](https://docs.sensu.io/sensu-go/5.0/guides/monitor-external-resources/), it seems that there is a difference between the $PATH used by `systemd` and `sensu-agent`:

**systemd**

![systemctl-agent-path](https://user-images.githubusercontent.com/898627/48374233-3abeda00-e692-11e8-8b98-9304fc4be339.png)

**sensu-agent**

![sensu-start-path](https://user-images.githubusercontent.com/898627/48374248-44484200-e692-11e8-9116-768c0eee092e.png)

If one has to use `sensu-agent start`, or chooses to use this over an operating system service manager (or wouldn't have access to one), then this particular check would not work due to the differences in the respective paths. 

Are these expected to be different? Is this simply a case of using the sensu-agent workflow when we should be using an OS service manager instead?

**Comment by echlebek** [comment]
I think it's likely that this comes down to a difference between the user launching systemd and the user launching sensu-agent. They may have different PATHs defined.

In trying to verify this, I think I might have found a related bug.

https://github.com/sensu/sensu-go/blob/master/agent/check_handler.go#L91

The comment implies to me that the PATH variable should be appended to, whereas I believe this would cause it to be replaced by the PATH specified by the last asset or check.

**Comment by asachs01** [comment]
@echlebek so would the change here be to append the path? I imagine that if we're providing guides where we rely on an OS service manager to handle things, but someone may be using a container, we may run into the same issue of paths differing or seeing errors re: a binary not being in a path.

**Comment by echlebek** [comment]
I think that the agent should have the same PATH as the user that executed it, unless the PATH is amended by a Check's EnvVars or an Asset's.

Can you try to see if you can run the check that wasn't working directly from the command line?

**Comment by asachs01** [comment]
@echlebek so the check (as it currently stands) doesn't dump the output to STDOUT:

```
#!/usr/bin/env bash

target=$1

curl --silent --connect-timeout 5 $target > /dev/null
if [ $? -ne 0 ]; then
  exit 1
fi

exit 0
```

But, as a user, I can run it just fine:
```
[asachs@k8s000 ~]$ /usr/local/bin/http_check_silent.sh https://sensu.io && echo $?
0
```
My $PATH for reference:
```
[asachs@k8s000 ~]$ echo $PATH
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/asachs/.local/bin:/home/asachs/bin
```

Using `sensu-agent start` from that user:
```
[asachs@k8s000 ~]$ sensu-agent start --backend-url ws://192.168.156.232:8081 --subscriptions linux-hosts
{"component":"cmd","error":"open /var/cache/sensu/sensu-agent/assets.db: permission denied","level":"fatal","msg":"error executing sensu-agent","time":"2018-11-14T15:27:36-06:00"}
```

Works fine w/ sudo:
```
[asachs@k8s000 ~]$ sudo !!
sudo sensu-agent start --backend-url ws://192.168.156.232:8081 --subscriptions linux-hosts

```
But still has a difference in path between using `systemctl` and `sensu-agent`:
![sudo-sensu-agent](https://user-images.githubusercontent.com/898627/48513718-80160f80-e82a-11e8-8b34-4643d724d6c7.png)

**Comment by echlebek** [comment]
You're executing the check by absolute path, so of course the PATH variable will not come into play here.

It seems clear that the way PATH works in the agent needs at least a review.

**Comment by grepory** [comment]
After some discussion with @echlebek, I think we understand the issue.

Given:

https://github.com/sensu/sensu-go/blob/d4ecf2e8ddef30988f352cf1c5ab1b2ff8a7fcca/agent/check_handler.go#L91

The behavior I would expect is this:

By default the environment of the child process (e.g. check, handler, etc.) is the environment supplied by the parent process. This is, I believe, fundamentally how spawning sub-processes works across all operating systems. If the shell's PATH is not what you want sensu-agent's PATH to be, then you have to specify it at runtime, e.g. `PATH=/usr/local/bin:/usr/bin:/bin sensu-agent start`. Your check output should reflect this change. If it does something else, please let us know if you're using any assets, if the check has env_vars specified, etc.

Now, because of the snippet above, what we're doing is that when we see assets or check environment variables, we're overwriting the parent environment, and on top of that we have write clashes between the assent environment(s) and the check environment variables. Eric and I propose that we:

- merge PATH, LD_LIBRARY_PATH, and CPATH
- everything else is overwritten
- the order of preference for variables is:
  - check environment
  - asset environment
  - parent process environment

As a concrete example, if I have the following set of environments:

```
check env = ["PATH=/usr/bin", "FOO=bar"]
asset env = ["PATH=/bin", "BAZ=quux"]
parent env = ["PATH=/usr/local/bin:/usr/bin:/bin", "FOO=foo"]
```

The resulting environment would be:

```
PATH=/usr/bin:/bin:/usr/local/bin # deduplication is, frankly, optional
FOO=bar
BAZ=quux
```

**Comment by grepory** [comment]
@apaskulin we'll probably need some help making sure this is adequately documented in probably more than one place.

@annaplotkin I'm moving this into the 5.0.0 milestone.

**Comment by jspaleta** [comment]
I full expect paths to be different when run as service versus run as an interactive user. systemd's default environment for all services will most likely be different than what you get in an interactive login shell in traditional linux installs.  This is entirely expected on most linux distros.   Interactive logins will generally tickle /etc/profile as part of login and that will do a lot of environment and path manipulation as part of that.   

The service environment for sensu-agent.service as we package them in beta8  can be customized using /etc/default/sensu-agent or /etc/sysconfig/sensu-agent by the local admin as they are defined to be optional environment files for the service. I currently have a custom /etc/sysconfig/sensu-agent  and sensu-backend with custom PATH defined to make it possible to use rubygem executables in a filesystem pocket I control.
