### ISSUE TITLE
Verify Slack and Influx handlers for GA

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2413]
Quick verification needed for GA on handlers that we got running with Beta8. Additional tickets to be created in the event that anything isn't functioning properly. 

https://github.com/sensu/sensu-slack-handler
https://github.com/sensu/sensu-influxdb-handler

**Comment by nikkiki** [comment]
Good news, both handlers are compatible with the candidate GA sha! I've created the following tickets to update the sensu-go version (just because GA > beta). These can be completed after we've released GA 🎉
- https://github.com/sensu/sensu-slack-handler/issues/6
- https://github.com/sensu/sensu-influxdb-handler/issues/13
