### ISSUE TITLE
Cluster admins need the ability to reset user passwords

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#2434]
Any user with the appropriate rights on the `users` resources should be able to reset the password of a user, without knowledge of its current password.

Right now, the `sensuctl user change-password` requires the user to enter the current password, which is not desired for security and practical reasons.

**Comment by majormoses** [comment]
This makes sense I am wondering if we want to create a specific role for user management I don't see one in the [defaults](https://docs.sensu.io/sensu-go/latest/reference/rbac/#default-roles). `admin` and `cluster-admin` would implicitly have access to these. Some other functionality to consider around user management roles would be setting up SAML and such since this is often managed by a different team who do not need general admin access in sensu.
