### ISSUE TITLE
Check auto_resolve configuration option

### ISSUE THREAD

**Issue by portertech** [sensu/sensu-go#2438]
Sensu Go does not support the Sensu 1.x Check configuration option `auto_resolve`.

From the [Sensu 1.x documentation](https://docs.sensu.io/sensu-core/1.6/reference/checks/#check-attributes):

> When a check in a WARNING or CRITICAL state returns to an OK state, the event generated by the WARNING or CRITICAL state will be automatically resolved. Setting auto_resolve to false will prevent this automatic event resolution from occurring. This is useful in situations where you want to explicitly require manual resolution of an event, e.g. via the API or a dashboard.

Should Sensu Go provide such configurable functionality?

**Comment by cwjohnston** [comment]
I believe this functionality remains a requirement for certain varieties of checks, for example log monitoring. 

Both sensu-plugins' `check-log.rb` plugin and the monitoring-plugins.org `check_log` plugin make use of stored state to keep track of log lines that have already been "seen".  This means that each execution of these plugins is ignoring any previous occurrences of the specified pattern, returning OK if there haven't been any new occurrences since the plugin last ran.

Without support for turning off `auto_resolve`, operators will be in a situation where events generated by these checks are frequently resolved by the next execution, creating a false sense of security when the event is resolved despite the likelihood that the underlying condition which lead to the log message being created is still an active concern.

**Comment by echlebek** [comment]
We need to add the concept of manual or forced resolution, before we can support this use case.

**Comment by cwjohnston** [comment]
This capability was recently requested by a prospective customer. @jspaleta [phrased their request this way](https://sensu.slack.com/archives/C052T0566/p1563410794019700):

> can we create "latching" alerts... that stay in an alerted state until a human manually resolves them instead of auto-resolving[?]

**Comment by ltoning** [comment]
Hi, would make sense if this issue has some kind of resolution in the future.  Like cwjohnston already mentioned a valid case 
like log file monitoring and the feature somehow was available in Sensu 1.x. Are there any options?
