### ISSUE TITLE
Keepalive events do not have a namespace in their metadata

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2465]
Keepalive events should use the entity's namespace in their metadata, but they do not.

**Comment by grepory** [comment]
I'd like us to look at defaulter functions and initializers for objects as a possible solution to this.

We already have a need for it for handlers and check configs (ensuring a default timeout exists for objects).

This will have implications in the CLI and documentation, but I would rather we solved this a single way across objects instead of doing it ad hoc in places where we create objects.

**Comment by echlebek** [comment]
This fits with a general strategy I've started of creating NewXXX functions for each type. Defaults should by assigned there as appropriate.

For now, the NewXXX functions simply create empty maps for labels and annotations, but we can start adding default values to them.

**Comment by echlebek** [comment]
This was fixed at some point.
