### ISSUE TITLE
agent retry logic (first connection) on multiple backends

### ISSUE THREAD

**Issue by nikkiki** [sensu/sensu-go#2533]
Looks like we might want to return `err` instead of `nil` on `L381`, so that it can be logged in `L390`. That code block appears unreachable.
https://github.com/sensu/sensu-go/blob/e3421f7ed050bfb3310f83a28aed5b9d85b4be64/agent/agent.go#L377-L391

I also noticed that on an agents first connection, it only attempts retry logic on one backend (provided by the `RandomBackendSelector`). I'm wondering if it would be beneficial for that agent to try connecting to other backends until its successful.. unless this isn't the actual/intended behavior already. https://github.com/sensu/sensu-go/blob/e3421f7ed050bfb3310f83a28aed5b9d85b4be64/agent/agent.go#L201

**Comment by cwjohnston** [comment]
## Expected Behavior

The agent will iterate over a shuffled list of backend URLs attempting to connect successfully. If a connection attempt fails, the agent will move on to the next backend in the list. Each connection attempt and the attempt's outcome are logged so that operators are informed as to why the agent is not able to connect. 

## Current Behavior

Agent selects a random backend from the list of backend-urls, but logs do not reflect connection attempts or any related failure messages.

## Possible Solution

* Add log messages when connecting which help operators to be aware of and diagnose connection attempts, retries and failures
* Modify agent behavior to iterate through the list of backend URLs as part of connection retry logic
* Bonus: add some form of backoff as part of retry logic, if not already present.


## Steps to Reproduce (for bugs)

1. configure an agent with multiple backend urls, some of which are known to be invalid (e.g. will refuse connections or timeout)
2. while watching the agent's log output, restart the agent
3. use `netstat -lnap | grep 8081` to determine which of the backends the agent is attempting to connect to
4. note that when the agent is attempting to connect to one of the known-invalid backends, there are no log messages indicating that a connection is being attempted, nor that the connection failed and/or was retried
5. note that the agent continues to retry the same backend url until it is restarted, instead of trying another backend from it's list

## Context

When the agent starts with this configuration, it seems to randomly choose a backend from this list of URLs (as described in the OP above), but there's no log message indicating that a connection is being attempted, that the attempt failed, nor that the connection was retried.


## Your Environment
* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 5.2.1
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): centos 7.4
