### ISSUE TITLE
Consider a `subscriptions` API endpoint

### ISSUE THREAD

**Issue by RamblingCookieMonster** [sensu/sensu-go#2589]
It might be useful for some folks to have access to a `subscriptions` api endpoint

## Expected Behavior

I can list subscriptions and associated items with a single API call

## Current Behavior

Even if I just want a list of subscriptions (not associations to their respective events, entities, checks), I must list all events, entities, and checks, and extract the subscriptions from these.  This is quite an expensive operation.

## Possible Solution

Create a `subscriptions` API endpoint that performs these computations on the backend, likely a much cheaper option than pulling all the data across the network to work with locally.

Ideally each subscription item would ideally include the name, and associated events, entities, and checks, at the least

## Context

Example use cases:

* Extract subscription names, audit and alert on subscription names in violation of naming convention
* Extract unique set of subscription names to identify these and avoid duplicating a subscription name with a slight variation
* Other activities where knowing the full set of subscriptions and associated items would be useful

**Comment by palourde** [comment]
Subscriptions are not an actual resources in Sensu, these are simply references in entities and checks. Maintaining and keeping track of all subscriptions would require a considerable amount of work because we would basically need to keep track of subscriptions that could be added and removed. I understand it's an expensive operation to make via the API but it wouldn't much easier to do within sensu-backend with the current storage solution (etcd). Because of that, this is not something that will be implemented anytime soon.
