### ISSUE TITLE
Feature Request: Support multiple files in sensuctl create

### ISSUE THREAD

**Issue by roganartu** [sensu/sensu-go#2631]
Allow repetition of the `--file` flag in `sensuctl create`, and/or support path globbing.

## Expected Behavior
```
$ sensuctl create --file base_checks.json --file disk_checks.json
```
Should create resources from both JSON files.

```
$ sensuctl create --file resources/checks/*/*.json
```
Should create resources from all `.json` files in child directories of `resources/checks` up to a depth of 1 (eg: `resources/checks/base/ping.json` and `resources/checks/network/arista.json`)

## Current Behavior
`sensuctl create --file` currently only supports loading a single file, which limits users' ability to structure their config-as-code JSON files, instead requiring they either put all config in a single file or add logic to their deployment to call sensuctl for each file (eg with `find` and `xargs` or similar).

## Possible Solution
Go supports basic globbing: https://golang.org/pkg/path/filepath/#Glob. It's not perfect (there's no double-star globbing) but this is how some other popular Go-based tools provide this support (eg: prometheus) so users are likely to be somewhat familiar with it.

The relevant function here is https://github.com/sensu/sensu-go/blob/master/cli/commands/helpers/input.go#L26 which is only used by the `create` command anyway. Since `create` operates on a JSON stream instead of a complete (ie: array) top level object, afaict implementing this could be done as follows:
1. Make the `--file` flag repeatable
2. For each flag value provided, expand the glob into a list of paths
3. Return an `io.Reader` that streams from the combined list of files, moving onto the next file when EOF is reached until there are no unread files remaining. This avoids the need to make any modification to the `ParseResources` function.

## Context
I came across this limitation while setting up a deployment pipeline for sensu config from a code repository. I think it will become more apparent with #2613 as users won't be able to make a separate call to `sensuctl create --delete <resource> --file` for each file without deleting things present in other files, forcing them to sacrifice structured config-as-code in order to use the `--delete` feature to keep resources in sync.

**Comment by roganartu** [comment]
Thanks for the workaround tip. Another option for people to consider in the meantime is to make your CI just cat files together (though this doesn't allow you to dynamically change namespaces). eg:
```
cat checks/**/*.json assets/**/*.json | sensuctl create
```
but I think it would be cleaner if `sensuctl` supported this natively.

**Comment by annaplotkin** [comment]
For the Sensu team to consider [possibly looking into K8s approach]

**Comment by ccressent** [comment]
@roganartu your "workaround" is actually what I would consider the proper, "Unix way" to go about this. It still allows to change namespaces (or any other field for that matter) on the fly: you need to add steps to your pipeline. See [this comment](https://github.com/sensu/sensu-go/issues/2826#issuecomment-494905906) for an example using `jq`. That being said, there seem to be a consensus that the UX is better if we provide means to achieve the same thing with `sensuctl` directly, usually with dedicated flags. 

Regardless, as @jkerry mentioned, there is also an ordering problem at play here and it's the main issue I see with implementing this: the order in which you `cat` your files (or use the flag suggested in this issue) has an influence on whether the command will fail or not. For example, consider the case where checks for namespace `A` appear before namespace `A` is created.

I think this is important to consider for UX, since, for example if we allowed globbing, your file names and layout would have an influence on whether the `sensuctl create` command succeeds or fails!

**Comment by echlebek** [comment]
Sean points out that we would like to understand and document the glob loading behaviour in Sensu classic, and prefer to emulate that behaviour to the greatest extent possible.

**Comment by nikkixdev** [comment]
Notes doc: https://docs.google.com/document/d/1_Zuz9_a4djz7_pPt5EeU3uBpB2lJBNstf1n-6TfGwMc
