### ISSUE TITLE
Create separate TLS config for dashboardd

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2642]
## Expected Behavior
The dashboard can use a separate TLS config from the API

## Current Behavior
The dashboard TLS config is aliased to the API TLS config

## Rationale
The dashboard should be allowed to present its own TLS certificate. Users may wish to host the dashboard on a different hostname than the API.

**Comment by gbolo** [comment]
I also support this idea.

**Comment by gbolo** [comment]
There are two simple solution for this:
- put a TLS reverse proxy in front of these components (like nginx) so that we can do SNI and reuse the same port. 
- use a wildcard certificate that to match the names of both the backend and dashboard

In order to support this change I will have to introduce at least two new flags: `--dashboard-cert-file` and `--dashboard-key-file`

Please confirm that the following logic makes sense:
 - if dashboard cert/key are specified and api cert/key are not then the dashboard starts with TLS while the api does not
 -if api cert/key are specified and dashboard cert/key are not, then by default the dashboard will use the same TLS config as the api (this is to maintain same behaviour of current release, if we don't care about this then we can allow the backboard to come up without TLS)

Once the behaviour we want is confirmed, I can work on this PR
