### ISSUE TITLE
Entity and Check information and visibility

### ISSUE THREAD

**Issue by autarchprinceps** [sensu/sensu-go#2674]
We have been looking at migrating to sensu-go. A major issue that stands in our way is, that there seems to be no way, aside from labels and annotations, to add custom information, let's say cloud metadata, non-agent based instance details, etc.
On the other hand, even if we were to flatten the maps of information to labels or annotations, which would be annoying enough, I cannot find either in the web ui.

**Comment by roganartu** [comment]
I'd like to echo the annoyance of losing the feature of deep custom information. We solve it by flattening custom attributes with a separator:
```
{
    "labels": {
        "foo": {
            "bar": "baz"
        }
    }
}
```
becomes
```
{
    "labels": {
        "foo.bar": "baz"
    }
}
```

This is a little annoying but not a huge deal for us. It would definitely be nice to have support for nestable attributes though, as well as non-string attributes (eg: some attributes make sense as lists, we don't have a good way to flatten those yet).

There's an existing `ExtendedAttributes` property on an Entity:
https://github.com/sensu/sensu-go/blob/master/api/core/v2/entity.pb.go#L39

but it's not suitable for this because:
- It's omitted from JSON responses and ignored in JSON requests, so can only be used internally or via the graphql endpoint
- It doesn't actually appear settable? Extended attributes appear to have been all but removed in https://github.com/sensu/sensu-go/commit/be7ea1d67eb990cfb0373d11882d34a375bb9190 so perhaps these references are just missed artifacts.

**Comment by calebhailey** [comment]
@autarchprinceps @roganartu curious if this is still presenting any challenges for you? We've held a pretty firm line on maintaining a simple/flat data structure for labels and annotations (all strings all the time), but we have added some quality-of-life things in the web ui (for example) for some popular use cases such as links, images, etc. 

![](https://user-images.githubusercontent.com/1707663/76572490-754ba900-6477-11ea-9be7-4b488fea445b.png)

Does this resolve the "visibility" aspect of this issue for you?

**Comment by roganartu** [comment]
I'd say that not having arbitrary JSON properties is still a pain point, though by this point we've mostly worked around them by reinventing the dot-separator wheel basically identically to how Elasticsearch handles these fields, as described in my original comment.

The reason this is painful for us is that our source-of-truth for entities is external to Sensu (specifically, Netbox: https://github.com/netbox-community/netbox) which supports arbitrary JSON in devices via the `device.config_context` field. Much of our other tooling leverages this arbitrary JSON extensively, and so we found ourselves needing it within Sensu entities for eg proxy entity matching and filtering etc. The sync tooling flattens this structure before storing it in Sensu entities, but it would be nice if it didn't have to.
