### ISSUE TITLE
Feature request: Multi-namespace assets

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#2861]
## Expected Behavior
As a user who's running multiple environments (dev, stage, prod), I'd like to create an asset that can be tied to multiple namespaces, rather than having to individually create an asset for each environment. This is especially useful when ensuring that each environment is consistent. 

## Current Behavior
Currently, I have to create an asset for each namespace individually.

## Possible Solution
Provide the ability to specify multiple namespaces in my asset yml/json file

**Comment by sureshsubramaniam** [comment]
Would be nice to have this feature reducing duplicate assets and definitions

**Comment by ff-pjha** [comment]
It will be really helpful if we have this as soon as possible. We have created more than 5 namespaces and we are repeating the checks in all namespaces.

**Comment by amccrea** [comment]
Upvote. We have 36 namespaces (one for each env, and we have 36 envs - prd, int, stg, 20 dev envs, etc). So defining our 12 base bonsai assets for each one (ruby runtime, cpu checks, network checks, etc) is doable but it's quite annoying to manage 450+ assets instead of 12. 

Also since we use Puppet, each resource in Puppet must be uniquely named, so each of those assets has to have a unique name. 

It would help immensely if we could just have the namespace field take an array, or better yet, "all".

**Comment by trombik** [comment]
it would be better if other resources support multiple namespaces. other than checks, i need shared entities for proxy entities. when someone in a namespace needs to monitor external resources with proxy, the real entity that runs checks must be in the same namespace. you then need to maintain the real entity.

as an sysadmin, i would like to provide shared entities for others in non-default namespace so that they can simply define proxy entities (and use shared checks, too) in the namespace and forget the real entities.

**Comment by trombik** [comment]
the issue is still valid, i guess.
