### ISSUE TITLE
Spike - curated namespace list

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#2872]
## Expected Behavior
As a Web UI, I expect to be able to know which namespaces a user has access to.

## Current Behavior
The user can see a list of all namespaces.

## Spike
Determine the feasibility of transmitting a filtered list of namespaces to the frontend. This could be done with an auth sideload, or a new special endpoint.

**Comment by palourde** [comment]
Here's the result of my spike:

There's only a single way of determining which namespaces a user has access to. It is fairly similar to the current authorization mechanism but instead of trying to find the first rule that authorizes the request, we need to loop through all bindings and accumulate all the resources (in our case, namespaces) a given user has access to.

The high-level logic looks like this:

1. Get all `ClusterRoleBinding` resources
	- For each binding, determine if the subject matches. If so, get the corresponding `ClusterRole`
		- If the `ClusterRole` gives access to the `namespace` resource, it means the user has access to all namespaces. Therefore, we can **return all namespaces**.
2. No matching `ClusterRoleBinding` was found so get all `RoleBinding` resources across all namespaces and build an empty array of namespaces
	- For each binding, first check if its namespace is already within the array of namespaces. If so, skip it, otherwise determine if the subject matches. If so, it means the user has access to this namespace (we don't care about the actual resources he has access to) so add the binding's namespace to the array and continue with the next binding
	- **Return the curated array of namespaces**

Regarding the implementation details, I've reviewed how Kubernetes deals with the `can-i` functionality and our current authorization implementation. Basically, we simply need to decouple our [authorization logic](https://github.com/sensu/sensu-go/blob/c18b852bae6b805da4ce743b3388d63128e1fc9e/backend/authorization/rbac/rbac.go#L20) from the "rule resolver" mechanism.

The way Kubernetes does it is kind of clever. They have a [`VisitRulesFor`](https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/registry/rbac/validation/rule.go#L178) method that takes a _visitor_ function. This visitor function is called whenever a rule matched our user and decides what to do next, whether it's  [authorizing a user](https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/plugin/pkg/auth/authorizer/rbac/rbac.go#L62) or simply [accumulating the rules](https://github.com/kubernetes/kubernetes/blob/a3ccea9d8743f2ff82e41b6c2af6dc2c41dc7b10/pkg/registry/rbac/validation/rule.go#L128).

By doing something like this, we could "easily" implement a curated list of namespaces and prepare the way for providing users with their permissions (which the dashboard could consume) and/or a `can-i` functionality.

**Comment by palourde** [comment]
Issue moved to [sensu/sensu-enterprise-go #406](https://github.com/sensu/sensu-enterprise-go/issues/406) via [**ZenHub**](https://www.zenhub.com/)
