### ISSUE TITLE
Pagination - Audit codebase for queries which can optimized using API pagination.

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#2889]
Now that we have the initial implementation of API pagination, we need to conduct an audit of the codebase to understand which queries could be optimized using pagination.

**Comment by echlebek** [comment]
These are the problematic spots in the code for data access:

https://github.com/sensu/sensu-go/blob/master/backend/schedulerd/entity_cache.go#L74
https://github.com/sensu/sensu-go/blob/master/backend/tessend/tessend.go#L316 (solved in a current PR)
https://github.com/sensu/sensu-go/blob/master/backend/keepalived/deregisterer.go#L36
https://github.com/sensu/sensu-go/blob/master/backend/keepalived/keepalived.go#L140

The last one is particularly problematic because we don't have a way to request for pagination in the keepalive store yet.

**Comment by ccressent** [comment]
I found 2 additional potential spots:
- https://github.com/sensu/sensu-go/blob/5.6.0/backend/schedulerd/check_watcher.go#L87
- https://github.com/sensu/sensu-go/blob/5.6.0/backend/schedulerd/executor.go#L349

These concern Checks and Hooks and are therefore less problematic than something that retrieves, say, all the Events.

I used the following ripgrep invocation, if that's useful to anyone else:
```
$ rg --glob '!backend/store' --glob '!vendor' --glob '!mock*' --glob '!dashboard' --glob '!*_test.go' --glob '!cli' --glob '!*.pb*' 'Get.*s(B.*)?\('
```

For `GetEntities()` and `GetEventByEntities()`, the spots mentioned by @echlebek retrieve all the objects from the store no matter what. It's not clear to me that retrieving all the objects in one go would be slower than querying the store page by page, at least when talking to an embedded etcd. My next step is to write a benchmark to compare the difference between the two approaches on, say, 10,000 or 100,000 entities.

I'm not very familiar with the entity cache, but if its creation is a bottleneck, maybe an alternative approach would be to _not_ populate it with _all_ the entities during its initialization. Instead start empty and add entities to the cache as they are retrieved. That would also potentially greatly reduce the memory footprint of the cache.

For the `GetFailingKeepalives()` case, I can add pagination support in that store if we need to, that's easy. We can then solve this case the same way we decide to solve the others: do nothing if the benchmark shows little difference or loop through pages if that's noticeably faster.
