### ISSUE TITLE
Cancelled contexts in watchers cause high CPU usage

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3012]
We discovered during 5.7.0 QA where upon removing 1000 proxy entities, the CPU usage would remain extremely high on at least one backend node. Here's the graph of the profile the reliability team took against a 5.7.0 cluster: [caviar_pprof.pdf](https://github.com/sensu/sensu-go/files/3237850/caviar_pprof.pdf)

From @ccressent:

> Basically, it boils down to this loop going haywire: https://github.com/sensu/sensu-go/blob/0d61cbddf963c2c62d04ccb56b23d9605ac4d770/backend/store/etcd/watcher.go#L83 Checking `ctx.Err()` very rapidly causes all this time spent locking/unlocking. There are things I want to try to finishing understanding what's going on, but like you, I've been unable to _reproduce_ the problem in the first place...

Here's some things we could try to reproduce the problem:

- [x] Try to reproduce this problem against 5.9.0
- [x] Try to reproduce this problem against 5.7.0
- [x] Try to reproduce this problem with a cluster first deployed with 5.6.0 and then upgraded to 5.7.0 to simulate the conditions against which QA was done.

**Comment by palourde** [comment]
I was unable to reproduce this issue against a 5.9.0 cluster. Is it possible this issue was fixed in 5.8.0 or 5.9.0? Could it be related to the serialization changes we made in 5.7.0?

**Comment by ccressent** [comment]
@echlebek made a good catch: the [limiter used in that function](https://github.com/sensu/sensu-go/blob/master/backend/store/etcd/watcher.go#L82) should be _inside_ the `for ctx.Err() == nil { ... }` loop! I'd still like to find a way to reproduce the issue so that we can "prove" that reworking the limiter fixes it.

**Comment by palourde** [comment]
@ccressent I've deployed a 5.6.0 cluster, upgraded to 5.7.0, then created/destroyed 1000 proxy entities without any success 😓. The load always quickly come back to almost nothing.

**Comment by ccressent** [comment]
Based on my testing and profiling, this issue is caused by a combination of 2
things: a failure of the `etcd` client to properly report that a watcher is
effectively dead, and our code assuming that it can always detect when a watcher
dies.


<a id="orgc7f99c1"></a>

### `etcd`'s watcher can fail to properly report their death

As reported in [this issue (still open)](https://github.com/etcd-io/etcd/issues/8980), watchers can fail to properly report
that they are not watching anything anymore. Despite the maintainer's claim that
giving a client multiple node endpoints should allow for automatic failover, I'm
unable to observe this behaviour.

These types of watchers waiting indefinitely in the client can also be triggered
by short network connectivity issues!


<a id="orgb64da4d"></a>

### Our code assumes we will always detect a watcher's death

In a nutshell, it assumes that the context's error will be non-nil if the
watcher's channel has been closed. This is not always the case. This leads to
our code entering a tight loop that tries to read a closed channel.

We seem to have modelled our code on the examples provided in the `etcd`
documentation, but those examples are bad in the sense that they only show how
to grab values from the watcher's channel, not how to completely manage the life
cycle of the watcher.


<a id="org2f8d17d"></a>

### How to reproduce

It boils down to managing to make `etcd` create those "zombie" watchers. Once
that happens, any goroutine in our backend that's using one of those zombies
will go haywire.

I've found two ways to create a zombie: overloading `etcd` and temporary
severing the connection between some cluster members. The later is much faster
and much simpler to execute: temporarily adding an appropriate firewall rule
does the trick.

    sudo iptables -A INPUT --dport 2380 -j DROP

This will make the backend it's executed on disappear from the `etcd` cluster as
far as the other members are concerned. Removing that rule makes the backend
reappear:

    sudo iptables -D INPUT --dport 2380 -j DROP

From then on, `sensuctl cluster health` will report all the backends as
connected and healthy, but some of them might still be using zombie watchers in
a tight loop, creating a spike in CPU usage.


<a id="org7a7ad17"></a>

### Potential fixes


<a id="org3b1d549"></a>

#### Periodically throw away all the watchers

This is the approach taken [by these guys.](https://github.com/gazette/core/issues/24) This gives an upper bound on the
length of time zombie watchers might be used. I'm not sure this is great from a
correctness standpoint: until a zombie watcher is reaped that way, it won't
report any changes to the key that's being watched&#x2026; But at least the system
eventually corrects itself.


<a id="org480aa1f"></a>

#### Better attempt to detect a disconnection

The `etcd` maintainers mention trying to use Sessions to do that. According
to them, Watchers were never designed to be able to detect disconnections and
they just retry forever ([see this issue](https://github.com/etcd-io/etcd/issues/5985)).

Alternatively, we might be able to use the `WithProgressNotify()` option on the
watcher and then time it out if there is no notification for a given amount of
time, 1 minute being suggested. Though one of the maintainers mentions this is a
bad idea in general and suggest using Sessions again.


<a id="org2314497"></a>

### Interesting links

-   <https://github.com/etcd-io/etcd/issues/8980>
-   <https://github.com/etcd-io/etcd/issues/5985>
-   <https://github.com/etcd-io/etcd/issues/6699#issuecomment-255476329>
-   <https://github.com/gazette/core/commit/e21d111ebe443abf9bf177c07881b9ce68824532>
-   <https://github.com/etcd-io/etcd/issues/8181>
-   <https://github.com/etcd-io/etcd/issues/8495>
