### ISSUE TITLE
Store a unique sensu cluster id

### ISSUE THREAD

**Issue by annaplotkin** [sensu/sensu-go#3039]
We need to ensure that cluster IDs are unique and accurately represented as such.

**Comment by nikkiki** [comment]
Due to https://github.com/etcd-io/etcd/issues/10814, the ClusterID provided by etcd is not necessarily unique. This is problematic primarily for Tessen, where we rely on cluster id uniqueness to differentiate clusters.

**Proposed solution/workaround:**
Store a [randomly generated UUID](https://godoc.org/github.com/google/uuid#New), `SensuClusterID`, at `/sensu.io/cluster_id`. This value should be populated at start up IFF an entry does not already exist at that store (first write wins in a multi-node cluster). The `SensuClusterID` must be exposed by the API and by sensuctl, via new/existing endpoints and commands.
