### ISSUE TITLE
Silenced Entries Cache

### ISSUE THREAD

**Issue by palourde** [sensu/sensu-go#3042]
While performing benchmarks, we realized that [queries](https://github.com/sensu/sensu-go/blob/613f31c430c7d2b8d00de82e8815756f68f118c9/backend/eventd/silenced.go#L24) to determine if an event is silenced create a bottleneck in etcd.

We should implement a caching mechanism for silenced entries, similar to what we have for entities. I've wrote a [PoC](https://github.com/sensu/sensu-go/commit/9aef5954d332aeff44b683d58ce1ed0c2295d545) 1 month ago, but the entities cacher changed since then so it will require a bit more work.

**Comment by echlebek** [comment]
In benchmarking, disabling silenced lookups resulted in a dramatic reduction in etcd reads, especially as events scaled. With silenced entries being looked up for each event, reads scaled linearly, resulting in thousands of reads under load. Without these lookups, etcd reads become a function of agent inventory size.

Eliminating this lookup can save a large amount of disk I/O, network traffic, and CPU usage.

Posted below are some screenshots from testing the enterprise edition of Sensu Go with a PostgresQL event store, introduced in order to achieve a higher event throughput. Removing silenced reads enabled us to achieve a much higher throughput overall. Reducing these reads should help the OSS/Free version's performance as well.

![Screenshot from 2019-06-11 14-01-36](https://user-images.githubusercontent.com/1633772/59366725-99633980-8cef-11e9-99c0-70a17f818aec.png)
_above, a screenshot showing linear growth in etcd reads with silenced entry lookups enabled_

![Screenshot from 2019-06-11 17-46-33](https://user-images.githubusercontent.com/1633772/59366738-9d8f5700-8cef-11e9-86fb-f0490b1e65ec.png)
_above, a screenshot showing a constant number of etcd reads with silenced entry lookups disabled_
