### ISSUE TITLE
sensuctl dump silently discards errors

### ISSUE THREAD

**Issue by echlebek** [sensu/sensu-go#3236]
## Expected Behavior
sensuctl dump will report errors when they are encountered

## Current Behavior
sensuctl dump silently discards all errors, and returns a 0 status code

## Possible Solution
Use the API client instead of wrapping the command line tools

## Steps to Reproduce (for bugs)
1. run sensuctl dump against a backend that is not running
2. observe that no output is produced, and no error status occurs

## Context
When trying to dump postgres configuration, an HTTP error was occurring but I was unable to tell what it was.

## Your Environment
Fedora Linux

**Comment by nikkixdev** [comment]
https://github.com/sensu/sensu-go/commit/0ff13a13b1bc72e7c62c05d8e7ccd104ed397073 and https://github.com/sensu/sensu-go/commit/a961f007821542ec85d07fca61ef621f3d3e6d0d had to be reverted because they caused unforeseen issues with enterprise issues that was blocking a release. https://github.com/sensu/sensu-enterprise-go/pull/636 is still open but will need to be addressed as well. Reopening this issue for re-implementation at a later time.
