### ISSUE TITLE
Compiling open source version fails when improperly tagged

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#3244]
Version 5.12.0 was tagged as v5.12.0 which causes a build failure when using build.sh.

## Expected Behavior

When running build.sh to build open source version, the tagged version should work.  Either the in `version/cmd/version/version.go` should take this into account *or* more care should be taken to maintain consistent tagging of releases.  It appears that so far only versions 5.10.1 and 5.12.0 have been improperly tagged.
## Current Behavior

When attempting to build from source the following error is reported:

```
Building backend for linux-amd64
2019/08/29 16:21:07 Could not determine base version from "v5.12.0"
exit status 1
```
## Steps to Reproduce (for bugs)

1. Clone the open source sensu-go repository
2. git checkout v5.12.0
3. ./build.sh build_backend

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method (packages, binaries, docker etc.):
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by amdprophet** [comment]
Hi @nixwiz,

This was overlooked by us when we made the decision to start tagging with the `v` prefix for go modules compatibility. We are planning to remove `build.sh` and `build.ps1` as they're no longer necessary for our build pipeline. The good news is that you should now be able to build the project by using `go build`:

```
go build ./cmd/sensu-agent
go build ./cmd/sensu-backend
go build ./cmd/sensuctl
```

I've opened https://github.com/sensu/sensu-go/issues/3245 so that we can add these instructions to our README.

**Comment by nixwiz** [comment]
Thanks for that @amdprophet, I'll close this issue then.
