### ISSUE TITLE
Expose embedded etcd cluster member discovery options

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#3327]
## Feature Suggestion

Add backend CLI flags and options for `discovery` and `discovery-srv` etcd options

e.g.

`--etcd-discovery https://discovery.etcd.io/3e86b59982e49066c5d813af1c2e2579cbf573de`

`--etcd-discovery-srv example.com`

## Context

Clustering Sensu Go backends under automation is difficult because these discovery mechanisms built-in to etcd are not exposed in the backend.

**Comment by ccressent** [comment]
While I'm at it, also adding:
- `--etcd-discovery-srv-name`
- `--etcd-discovery-fallback`
- `--etcd-discovery-proxy`

As described [in the etcd documentation](https://etcd.io/docs/v3.3.12/op-guide/configuration/#discovery).

**Comment by ccressent** [comment]
After checking what the fallback and proxy options do, I think I shouldn't add them at all: it looks like if the "proxy" value is used for fallback, etcd is then limited to its v2 API. That won't work with our system at all!

What I suggest we do is the following: add `--discovery`, `--discovery-srv` and `--discovery-srv-name` only and internally force the fallback option to "exit".

That means that the `--discovery-proxy` option is not needed since it will never be used, and that also means that if discovery fails, the backend won't start at all and error out. Which is the only reasonable course of action since we can't fallback to the proxy and be limited to the v2 API anyway!

**Comment by ccressent** [comment]
While the `--discover-srv-name` flag is available in etcd 3.3.17 (the version we currently use), its associated field in [`embed.Config`](https://github.com/etcd-io/etcd/blob/v3.3.17/embed/config.go#L172-L174) does not appear until 3.4. Probably an oversight on their part...

For now we're back to only adding `--discovery` and `--discovery-srv`.
