### ISSUE TITLE
Silences on subscriptions don't always work

### ISSUE THREAD

**Issue by steveberryman** [sensu/sensu-go#3356]
## Expected Behavior
If I set a silence on `staging:*` all hosts with this subscription should be silenced

## Current Behavior
There are a number of subscriptions between the various entities checking in. I'm not sure it this is affecting anything but it seems worth noting.

If I set a silence in the UI on `staging:*`, the silence gets listed but the entities aren't showing up as silenced. Other subscriptions i've tested seem to work fine. Additionally `staging` doesn't show up in the dropdown of subscriptions. There are possibly others missing too, which might exhibit the same issue.

## Steps to Reproduce (for bugs)
Unsure how to reproduce on another system. I have 25+ subscriptions between the various entities. 
Not all of these appear in the dropdown on the silences UI page. 
Setting a silence on one that doesn't appear doesn't seem to actually set a silence.

## Your Environment
Ubuntu 18.04
Sensu 5.14.0-6578
79 entities
~ 4-8 subscriptions per entity
89 unique subscriptions total

**Comment by roganartu** [comment]
I have experienced this bug too, but it only seems to happen with silences created via some custom tooling we have.

This issue prompted me to dig into the source a little, and I believe I have at least found the source of my particular issue. Chatted a bit with @steveberryman in the Slack and it looks like it's the same cause as here too so I've detailed my findings below.

### Summary

It looks like the cause is roughly:
1) entity has lots of subscriptions
2) check only has one, or a subset of those entity subscriptions
3) silence is applied to a subscription on the entity that isn't on the check

### Details

The function that determines whether any individual `silenced` entry applies to an event is:
https://github.com/sensu/sensu-go/blob/8a21de8d0cd336d81418bc1cb4c55ed855cfe1bf/api/core/v2/event.go#L319-L367

This is called by `eventd`.

I believe this specific line is the cause of this issue:
https://github.com/sensu/sensu-go/blob/8a21de8d0cd336d81418bc1cb4c55ed855cfe1bf/api/core/v2/event.go#L347

This prevents a silence for an entity subscription from applying to an event if the check object doesn't also have that subscription. This is surprising to me, and I believe not documented anywhere.

### Reproduction

This is untested, but it roughly matches how all the checks we run are scheduled (using templating). The important parts specifically are: create an entity with more subscriptions than the check, and then apply a silence to one of the subscriptions not present in the check.

1) Create the following entity
```
{
  "type": "Entity",
  "api_version": "core/v2",
  "metadata": {
    "labels": {
      "colo": "bar"
    },
    "name": "foo",
    "namespace": "default"
  },
  "spec": {
    "deregister": false,
    "entity_class": "proxy",
    "subscriptions": [
      "colo:bar",
      "environment:staging",
      "entity:foo",
    ],
}
```

2) Create the following check
```
{
  "type": "CheckConfig",
  "api_version": "core/v2",
  "metadata": {
    "name": "echo",
    "namespace": "default"
  },
  "spec": {
    "command": "echo 'hello'",
    "interval": 60,
    "proxy_requests": {
      "entity_attributes": [
        "entity.subscriptions.indexOf('colo:bar') >= 0"
      ],
    },
    "publish": true,
    "subscriptions": [
      "colo:{{ .labels.colo }}"
    ],
  }
}
```

3) Start an agent that subscribes to `colo:bar`
4) Observe that the above check is successfully scheduled and run on that agent
5) Confirm that the list of subscriptions in `event.check.subscriptions` of the resulting events only contains `colo:bar` as expected
6) Apply a silence to the `environment:staging` subscription
7) Observe the silence fail to apply to the event

### Context

The reason this causes my particular setup problems is that we only have proxy checks (that run from a handful of agents but against hundreds of proxy targets) and leverage templated check configs heavily. The result is that we have many subscriptions on all our entities, but a small subset of those subscriptions on our agents and checks, as it was thought that check subscription was only used for targeting agents not for controlling whether silences are applied.

@steveberryman's example of `staging` also matches this, in that I presume the checks are configured to run on everything (and hence have no `production` or `staging` subscription) and the `staging` subscription is simply added to all staging entities.
