### ISSUE TITLE
sensuctl add asset from Bonsai fails for 'v' prefaced asset versions

### ISSUE THREAD

**Issue by nixwiz** [sensu/sensu-go#3425]
When attempting add an asset from Bonsai via ```sensuctl asset add```, an asset that has its version prefaced with a 'v' will fail to download, as the 'v' is stripped from the requested URL.
## Expected Behavior

For internal sorting (latest/outdated check), stripping of the 'v' is appropriate, but it should not be removed from the requested URL.
## Current Behavior

The 'v' is being stripped from the URL causing a 404 error when attempting to add.
## Steps to Reproduce (for bugs)

1.  ```sensuctl add asset nixwiz/sensu-go-fatigue-check-filter:v0.2.2``` will fail, attempting a GET on the bonsai API for '/nixwiz/sensu-go-fatigue-check-filter/0.2.2/release_asset_builds'
2.  ```sensuctl add asset nixwiz/sensu-go-fatigue-check-filter:0.2.1``` will work

## Context

I recently changed the versioning of my filter asset to including the 'v' prefix on the version.   Following this, I am no longer able to use ```sensuctl asset add``` to add it from Bonsai.
## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):  sensuctl version 5.15.0, build 13884593ee08a7f25d7f66a8b71da61c529de014, built 2019-11-19T20:20:17Z 
* Installation method (packages, binaries, docker etc.):  binaries
* Operating System and version (e.g. Ubuntu 14.04):

**Comment by portertech** [comment]
We need to revisit the Bonsai work around tags with "v".

PING @jspaleta @amdprophet

**Comment by julian7** [comment]
I just found this error myself. I'm wondering whether it's a relative easy thing to fix:

- version names are thanking you, but they can be fetched from Bonsai
- sensuctl, however, uses Hashicorp's goversion library, which make versions uniform and comparable
- sensuctl then try to use this canonized version name to fetch assets from Bonsai, instead of using the raw version.

It can be fixed either in Bonsai (I can't see its source, but I bet this is not an isolated attribute, therefore changing its behavior might affect other subsystems), or can be fixed in sensuctl itself.

This is the path I see being way simpler: if `(*Asset).HasVersion(*goversion.Version) bool` is replaced with something like `(*Asset).SelectVersion(*goversion.Version) *goversion.Version`, which returns the original version coming directly from Fetch Asset API endpoint, its `.Original()` could be used to fetch Asset Version.

It worked well for me with exactly one Bonsai asset, if it counts.
