### ISSUE TITLE
`sensuctl edit` syntax inconsistent b/t resources

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3472]
## Expected Behavior

When editing a filter resource via `sensuctl edit filter`, I should be able to edit the filter resource definition.

## Current Behavior

When using `sensuctl edit filter`, I receive the error:

```
 sensuctl edit filter contact_ops 
Error: invalid resource type: filter
```

Instead of using syntax that is correct across resources, this seems to be the only resource that requires the filter resource to be plural:

```
sensuctl edit filters contact_ops
Updated /api/core/v2/namespaces/default/filters/contact_ops
```

## Possible Solution

Change the edit command to use syntax that is consistent with other resources.

**Comment by echlebek** [comment]
It's because the actual data type is called "EventFilter" or "event_filter". This is an unfortunate naming decision but there is not much we can do about it.

Some options:

* We could add an exception to `sensuctl edit` but then people would expect it to work in `sensuctl create`, this would be a bad call in my opinion.
* We could add exceptions wherever we notice the problem but we'd probably miss some.
* We could add an alias for EventFilter called Filter in the core/v2 API.
* We could rename the data type and increment the major version of Sensu.
