### ISSUE TITLE
sensuctl doesn't appear to honor proxy environment variables.

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3538]
From some testing that I've been doing, it doesn't appear that sensuctl honors the http_proxy or https_proxy variables set in a user's profile. Here's what I've done so far to lead me to this conclusion:

Test env:
* 1 proxy server (squid)
* 1 proxy client

On the proxy server, I ran a tcpdump after configuring squid. I could see traffic flowing through the main interface and I was getting responses from curls, apt-get updates, and other commands after setting the aforementioned variables on my client. However, when using sensuctl from the client, no packets appeared to be flowing from any "asset add" commands. While I could download assets and retrieve information on checks and other resources, none of the traffic seemed to go through the proxy server I had configured.

I believe this to be an issue with how we're using the go-resty library to send calls to Bonsai, and subsequently any Sensu deployment. The library does support the ability to use a proxy (https://github.com/go-resty/resty#proxy-settings---client-as-well-as-at-request-level), but from what I've seen in the code, it doesn't appear like we make any considerations for this.

**Comment by palourde** [comment]
It appears we are using a _really_ old version of Resty (v1.0.0), which doesn't support `HTTP_PROXY` & `HTTPS_PROXY` by default.

Without upgrading, we would have to either use the `SetProxy` method or provide our own Transport to Resty, which would be initialized with something like `Proxy: http.ProxyFromEnvironment`.

Otherwise, we could upgrade to the latest version (v2.1.0) which support these environment variables by default (I was able to successfully test it) however there was some [breaking changes](https://github.com/go-resty/resty/releases/tag/v2.0.0) introduced; I'm not sure how impacted we are by those.

**Comment by mildgrim** [comment]
I'd very much appreciate proxy support seeing as most of our clients running Sensu are also behind proxy, and the asset adding via sensuctl has worked a lot smoother/better in our in-house Sensu installation than manual download, mainly related to assets differing quite a bit in how they differ between linux distros and the confusion that causes around containerized installations for our users.
