### ISSUE TITLE
Linux 32-bit arm tarballs missing sensu-backend

### ISSUE THREAD

**Issue by jwoodrich** [sensu/sensu-go#3544]
I downloaded each of the Sensu Go ARM tarballs (5.17.1) for Linux and found that only the one for arm64 contained sensu-backend.

## Expected Behavior

The website describes the Linux downloads as having the backend, sensuctl, and agent.  I thought all three binaries would be in each of the tarball files.

## Current Behavior

The only files included for armv5, armv6, & armv7 are: CHANGELOG.md, LICENSE, README.md, sensu-agent, and sensuctl.

## Possible Solution

Include sensu-backend in the 32 bit tarballs?

## Steps to Reproduce (for bugs)

1. Navigate to https://sensu.io/downloads
2. Go to the Linux section
3. Download sensu-go_5.17.1_linux_armv7.tar.gz (32-bit), sensu-go_5.17.1_linux_armv6.tar.gz (32-bit), or sensu-go_5.17.1_linux_armv5.tar.gz (32-bit) 
4. Untar the tar.gz file using your favorite archive management tool.  I tested with both tar from the command-line and GNOME Archive Manager and had the same result.

## Context

I'm trying to evaluate Sensu Go on armv7 hardware (Raspberry Pi 3b) but cannot install the backend.  I've tried building it myself, but ran into other problems.  The end result is that I can't evaluate on this hardware.

## Your Environment

* Sensu version used: downloading 5.17.1 (sensuctl, sensu-backend, and/or sensu-agent):
* Installation method: binaries
* Operating System and version: Raspbian 10.2 armv7l on Raspberry Pi 3B

**Comment by chinochao** [comment]
I will reply since no one seems to be very active in issues. But it seems that sensu-go does not provides sensu-backend binaries for arm arch. I had to build arm arch.

**Comment by palourde** [comment]
Hi all!

Unfortunately sensu-backend is not supported on ARMv7 and below, mainly because etcd is considered as _unstable_ on this architecture. Additionally, as mentionned in [this comment](https://github.com/sensu/sensu-go/issues/3546#issuecomment-585396904), ARM on 32-bit systems has known bugs in Go.

For these reasons, we do not include the sensu-backend binaries in the commercially supported packages. However, nothing prevents you from building these binaries yourself: https://github.com/sensu/sensu-go#building-from-source.

Thanks
