### ISSUE TITLE
token substitution for assets URLs

### ISSUE THREAD

**Issue by tarcinil** [sensu/sensu-go#3639]
As it is possible for servers to cross security zones, it would be nice if I could use a label/annotation on the entity regarding when its assets would be stored.

## Feature Suggestion
As I have many subnets and security zones, sometimes the HTTP server can't always be outside the zone.  

## Possible Implementation
N/A

## Context
We have many servers that exist in PCI, PII, etc zones, and we can't allow them to leave the secure zone so we have syncing systems that bring things into the zone securely.  The use of filters only allows for a certain amount of flexibility, however, using entity informing to build the url is an easy option as we `ohai` information that sets the server's percieved sync host as a label/annotation

**Comment by calebhailey** [comment]
One alternative idea: you could create a multi-build asset with label/annotation-based filters. That should get you the same end result. 

If you ultimately need different asset URLs for different "zones", I presume this means you have asset servers mirroring those assets in those same zones? Have you tried creating asset definitions with N replicas of the assets - one for each zone (based on agent entity metadata)?

**Comment by nikkixdev** [comment]
See https://github.com/sensu/sensu-go/issues/2528 for discussion on adding token substitution to handlers. There are some pros and cons here, definitely needs more discussion.

**Comment by palourde** [comment]
@nikkixdev another one here too

**Comment by nikkixdev** [comment]
After further team discussion, we have decided that it makes a lot of sense to move forward with this feature, thanks for the idea @tarcinil!

**Feature spec:**
- [ ] enable token substitution on the entire asset struct (except SHA512)
- [ ] agent assets (checks, hooks) should be passed the agent entity
- [ ] backend assets (handlers, mutators) should be passed the backend entity
  - [ ] the backend "entity" does not populate 100% of fields, as many of them are irrelevant, decide if any missing fields need to be populated
- [ ] info log the backend entity information at startup
- [ ] info log the backend entity information if the asset is attempting token substitution against that entity
- [ ] audit handler/mutator execution logs to ensure they are at least info level
- [ ] identify if any changes are required in sensuctl due to the bonsai asset system
- [ ] refactor the generic token substitution code as a standalone library (it must be accessible by the backend and agent)
- [ ] allow certain fields to be omitted from performing token substitution (ex. asset.sha512)
- [ ] extend token substitution system for types other than strings (this is nice to have, but if this becomes a blocking factor, file a new issue for it and move on)
