### ISSUE TITLE
Allow a filter to execute an external script for more complex decision making

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3739]
Feature Suggestion

It would be good if filters provided the ability to optionally run an external script as an alternative to using the built in expressions.

This would allow more complex and feature rich filters, which are easier to manage.

## Possible Implementation

Allow the filters attribute of a Filter to accept a script which is executed.

The return code of the script can be inspected to signal whether the event should be passed to the handler or not.

It could even be used in conjunction with other expressions.

## Context

One use for this I am think of is to be able to query other systems or data for whether a particular event should generate an alert.

Currently the only way to do that would be to do it in a handler, when it is logically more something the filter should be doing rather than the handler.

**Comment by echlebek** [comment]
@ichilton we've been experimenting with adding more functionality to the filter execution environment to enable more complex filter behaviours. Just out of curiosity, would your use case be satisfied by one or more of the following, made available through the filter execution language?

* Ability to make HTTP requests (and deal with their responses)
* Ability to use the Sensu API in a read-only capacity (read events, entities, checks, etc.)
* Restricted file I/O, such as ability to read/write a scratch space.
* Connecting to a database.
* Other (???)

Rationale: since filters are typically executed very frequently, it would be advantageous to avoid forking new processes, especially if that process loads an interpreter like Python or Ruby.

**Comment by ichilton** [comment]
@echlebek Sorry, slow reply.

The things you list would be awesome! - and would cover most of the use cases I can think of. I still thing it would be handy to have the ability to use an external script as well, for ultimate flexibility - even if it was documented that it's preferred to use the other features for performance reasons.
