### ISSUE TITLE
OIDC provider does not appear to be compatible with Google's implementation of OIDC

### ISSUE THREAD

**Issue by asachs01** [sensu/sensu-go#3756]
## Expected Behavior

Be able to sign into Sensu using Google credentials/Google's OIDC

## Current Behavior

Google doesn't return a "groups" attribute, which seems reminiscent of the Enterprise Dashboard issue https://github.com/sensu/sensu-enterprise-dashboard/issues/124 . The lack of this attribute results in a user not being able to sign in with Google credentials.

**Comment by palourde** [comment]
For reference, once we ship https://github.com/sensu/sensu-enterprise-go/issues/1090, users should be able to authenticate via OIDC. That being said, groups will still be unavailable, simply because Google requires a special request; see https://github.com/dexidp/dex/blob/master/Documentation/connectors/google.md#fetching-groups-from-google for more details.

We would probably need to create a special provider kind for Google if we do wish to support those.

**Comment by portertech** [comment]
We did ship https://github.com/sensu/sensu-enterprise-go/issues/1090 (in Sensu Go 6.1.0), users are able to authenticate via OIDC. It does not support groups.
