### ISSUE TITLE
Allow a filter to use a .js file by path rather than just using runtime assets

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3786]
You can javascript files rolled in to an asset to build complex filters - that's a great feature.

The only way to do that currently seems to be to use a packaged asset and supply it as a runtime asset.

The two problems with this are:

- Its difficult for development, because each change/iteration needs to be packaged up, the asset definition updated in sensu and then generate events to test.

- I can't have the filter put in place (or generated with) configuration management.

## Feature Suggestion

It would be good to have a filter be able to use a .js file by path.

## Possible Implementation

Exactly as it works with checks - you can have a check command supplied at runtime by sensu assets, or you can have a check definition use a command by path, and it's assumed that it's already in place on the agent.

**Comment by echlebek** [comment]
We want to improve the asset workflow rather than encouraging people to load files off the disk. Otherwise, keeping scripts and binaries up-to-date on Sensu backends becomes a significant piece of technical debt.

There are plans to improve and automate significant parts of the asset creation workflow for Javascript assets, we are hoping this will make using Javascript filters more manageable.
