### ISSUE TITLE
Allow token substitution on integers

### ISSUE THREAD

**Issue by ichilton** [sensu/sensu-go#3788]
The documentation for token substitution states:

> As part of the substitution process, Sensu converts all tokens to strings. This means that tokens cannot be used as bare integer values or to access individual list items.

> For example, token substitution cannot be used for specifying a check interval because the interval attribute requires an integer value. Token substitution can be used for alerting thresholds because those values are included within the command string.

## Feature Suggestion

I'd like to request a way of using tokens on integers, namely the interval.

## Context

I'd like to have different intervals of a certain check for different entities.

Without being able to use token substitution and the value of a label or annotation in the interval field of a check, I can't think of a way of doing this without having separate, duplicate checks?

Simple example - I want to probe production hosts more frequently than development hosts. Or public facing services more frequently than internal only, or less important tools.

I'm currently going through an exercise of trying to use more generic checks with token substitution instead of having a long list of checks with lots of duplicates/very similar checks - but this limitation then limits my ability to do that, forcing me to have duplicate checks with just a different interval.

**Comment by portertech** [comment]
Hey @ichilton :wave: Thanks for the issue!

Token substitution with data types other than strings would require a significant refactor/rework. Maintaining schedulers per entity with dynamic intervals driven by token substitution is challenging (bugs!) and goes against Sensu's design (using subscriptions for request routing etc). Because of this, I am going to close this issue/request.
