### ISSUE TITLE
Allow extended configuration for the embedded gostatsd server

### ISSUE THREAD

**Issue by raags** [sensu/sensu-go#3983]
## Feature Suggestion

The embedded gostatsd server is quite convenient to collect and send metrics via the sensu pipeline. However, the available options are very basic. We need the ability to pass options to change statsd behaviour, for e.g. related to TTL, percentile calculation, flush alignment, prefix, etc. 

## Possible Implementation

One way could be to pass all args of the form `--statsd-*` to the server. There are many parameters, and maintaining them by hand as they change might not be easy.

## Context

I want to use the embedded statsd server, but am forced to use the defaults, and there are no options for customization.

**Comment by ccressent** [comment]
Hi @raags,

The team has a few questions/suggestions:

- Which configuration options do you want to change specifically?
- Why use the embedded server instead of your own, separate server that you could customize?

We want to avoid adding a lot of extra flags in the agent, especially if there are other ways for specific use cases to be supported, for example by running a separate statsd when you need very specific behaviour.

Keep in mind that the embedded statsd server is not necessarily a 1:1 match in term of configuration with the Atlassian statsd and is, as you stated, a convenience meant for simple use cases. It does not support all the configurations and options of a full-fledged statsd server, so we might not even be able to support the options you need!
