### ISSUE TITLE
Custom output for HTML parser appears on Web UI

### ISSUE THREAD

**Issue by raihanchdy** [sensu/sensu-go#4091]
HTML format appears on Web UI

<span style=color:red> Could not find file /test </span><br>

The above format of the output to appear correctly on mails subjects but not sure why the same output is appearing on UI. In my opinion, Web UI should show below Output

 Could not find file /test

**Comment by portertech** [comment]
I am having trouble understanding the issue. Is the Web UI rendering HTML check output? Please take a screen shot.

**Comment by raihanchdy** [comment]
![image](https://user-images.githubusercontent.com/31199957/99486497-4b457180-298a-11eb-99a8-988eb563ab5d.png)

**Comment by raihanchdy** [comment]
Hi,

Did you get a chance to look into the issue?

**Comment by raihanchdy** [comment]
Please let know if you have any update.
Due to this issue, even mail body is not getting parsed into the proper format.

The same HTML output works very well in sensu core.

**Comment by raihanchdy** [comment]
If I manually copy the html output then formatting works but if I load the same output using {{ .Check.Output }} then HTML parser does not work.

Please check and do let me know.

**Comment by mcbsd** [comment]
I don't think that output "box" in WebUI is meant to render HTML output - most probably not and I don't see a reason for it anyway at this place.

**Comment by rehanch178** [comment]
Sensu go uses same output for webui and mail body.
I am rendering output in html format for mail body not for UI. 

My outputs are not one liner that I can simply output it. Look at my output which is bit complex and I need html parser to work properly

**Comment by calebhailey** [comment]
Hi there. It seems this is not an issue with Sensu itself, but with the check plugin/configuration. It seems that you want to generate HTML email notifications, but not display the HTML in the web UI. This is possible and usually quite simple, but to help you we'd need to see your configuration to help troubleshoot. 

Since this doesn't appear to be a bug in Sensu itself, I'm going to close this issue. If you still need help, please post a question in the [Sensu a community Discourse](https://discourse.sensu.io) where someone from Team Sensu or another Sensu user can help you. 🙂

Thank you!
