### ISSUE TITLE
Entity label key case defined in agent.yml is not honored

### ISSUE THREAD

**Issue by cwjohnston** [sensu/sensu-go#4096]
## Expected Behavior

Labels defined in agent.yml are faithfully reproduced in the resulting entity resource.

## Current Behavior

Label keys defined in agent.yml are mutated to lowercase in the resulting entity

## Steps to Reproduce (for bugs)
1. define a label containing uppercase letters in agent.yml
2. use sensuctl or API to retrieve the corresponding agent entity resource from the backend
3. note that the labels returned by the backend are have been mutated to lowercase
4.

## Context

![image](https://user-images.githubusercontent.com/148017/99832259-7e6c3a00-2b1d-11eb-9558-bbaa0e94fc1c.png)

Eric says:

> This might be a side effect of how cobra works, since it supports setting these things via environment variables
> I'm betting sensuctl create does not work like this

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent): 6.1.3
* Installation method (packages, binaries, docker etc.): packages
* Operating System and version (e.g. Ubuntu 14.04): Centos 7

**Comment by palourde** [comment]
This is in fact a limitation of Viper; there has been an issue opened for the past 3 years: https://github.com/spf13/viper/issues/411

I honestly don't see a way to fix that within sensu-go itself, unless we decide to either:

1. Make labels & annotations case-insensitive (probably not straight-forward because a couple of features rely on labels)
2. Fork Viper (might be a bit complex because Viper is case-insensitive by default)

Thoughts?

**Comment by amdprophet** [comment]
This likely won't get fixed unless we replace our use of Cobra & Viper with something else. I've opened https://github.com/sensu/sensu-docs/issues/2925 to document this limitation. Closing this as `wontfix` for now.
