### ISSUE TITLE
Restore ability to merge configuration for use in filtering

### ISSUE THREAD

**Issue by majormoses** [sensu/sensu-go#4188]
## Use Case

As I showed in my [Sensu Summit 2018 Talk](https://docs.google.com/presentation/d/1ukKadPwJYuFnvF7Sp_XbZYj_arpzxqrYOik7Jvbok2E/edit#slide=id.g3cbb0744a5_0_191)

1. define a generic check (cpu, disk, etc)
2. on a per entity basis override config via labels
3. Use that same information in the filters

Here is a relatively straight ward example using older syntax but the same applies to the newer sensu-go syntax.

On the check definition:
```json
{
  "checks": {
    "check_cpu": {
      "command": "check-cpu.rb -w \":::cpu.warn|80:::\" -c \"cpu.crit|90:::\" --sleep 5",
      "subscribers": ["base"],
      "interval": 30,
      "occurrences": ":::cpu.occurrences|4:::"
    }
  }
}
```

On an agent/entity:
```json
{
  "client": {
    "name": "i-424242",
    "address": "10.10.10.10",
    "subscriptions": ["base", "etl"],
    "safe_mode": true,
    "cpu": {
      "crit": 100,
      "warn": 95,
      "occurrences": 10,
    }
  }
}
```

With the old occurrences filter we were simply able to up the thresholds on a per entity basis and then it would only alert when the occurrences matched or exceeded that value rather than the default. This needs to work for all plugins regardless of the language the plugin (check, handler, etc) is implemented in.

**Comment by calebhailey** [comment]
Thanks for opening this issue, @majormoses. Much appreciated. 

For the @sensu/engineering team, here's some additional context (which Ben and I had discussed via DMs): 

There are several moving parts here, but I think the **TL;DR** is that the various differences between Sensu Core/Classic and Sensu Go are _mostly_ red herrings (though I'll address them below). Ben's business requirement is to facilitate a data-based solution for occurrence filter configuration (and overriding that configuration on a per-check or per-entity basis). In the end I think the [fatigue check filter](https://bonsai.sensu.io/assets/nixwiz/sensu-go-fatigue-check-filter) or something like it is pretty close to what his team needs. 

**The long version...**

Ben and team's main requirement is a solution for per-check and per-entity occurrence filtering configuration _and_ configuration-overrides (NOTE: in practice occurrence filtering basically means "initially handle this event on the `nth` occurrence, and only handle it again every `nth` subsequent occurrence"). In Sensu Core/Classic the configuration field that was used to manage occurrence filtering was semi-officially supported (only "semi-officially" because Sensu resource definitions weren't strongly typed - they were just JSON _data_ that you could add any random field to); in the case of `occurrences` this was eventually documented in the official Sensu Docs, but no code in the [sensu/sensu](https://github.com/sensu/sensu) project actually did anything with this data. In Sensu Go there is no `CheckConfig.Spec` field for configuring occurrence thresholds, but we probably also don't need one. 

Because Sensu Go has strongly typed resources _and_ structured data (labels and annotations), we have approached configuration and configuration-overrides a bit differently (or perhaps just the natural evolution of the conventions the community adopted around Sensu Core?). The [Sensu Plugin SDK](https://github.com/sensu-community/sensu-plugin-sdk) and all plugins that are developed using the SDK offer support for reading plugin command flag values from annotations, with built-in support for overriding configuration values on a per-check or per-entity basis. For example, the Sensu Slack handler `--channel` flag can be set in the handler definition (see https://github.com/sensu/catalog/blob/main/pipelines/alert/slack.yaml#L49 for example), but you can override this flag by setting the `sensu.io/plugins/slack/config/channel` annotation on a per-check or per-entity basis. See [here](https://github.com/sensu/sensu-slack-handler#annotations) for more information. 

While this solution in the Sensu Plugin SDK works for checks, hooks, mutators, and handlers – the requirement in question is regarding filters, which are strictly Javascript expressions. The good news and bad news there is that an SDK really isn't required to evaluate event payloads since processing JSON is effectively "native" in Javascript land; having said that, an SDK/library or built-in helper functions for things like configuration overrides would be nice. In the interim, basically no changes to Sensu Go are required to implement the desired occurrence filtering logic that Ben's team is after. The EventFilter reference documentation has some useful information for developing custom filters that helps explain why this is the case: 

- [Built-in JavaScript functions](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/filters/#build-event-filter-expressions-with-javascript-execution-functions) 
- [Using JavaScript libraries with Sensu filters](https://docs.sensu.io/sensu-go/latest/observability-pipeline/observe-filter/filters/#use-javascript-libraries-with-sensu-filters)

Ben and I also discussed a handful of other related topics, but in the end _I think_ we determined that @nixwiz's excellent [fatigue check filter](https://bonsai.sensu.io/assets/nixwiz/sensu-go-fatigue-check-filter) is pretty close to what his team is looking for. It sounds like there are some subtle differences in how that filter works and [what they were used to](https://github.com/sensu/sensu-extensions-occurrences/blob/master/lib/sensu/extensions/occurrences.rb), so perhaps the best path forward is to collect that feedback and see if it can be addressed in an update to Todd's filter (and/or the creation of a new/alternate occurrence filter plugin). 

> _SIDEBAR: Regarding references to "merging" configuration, this may not be a familiar term to Sensu Go users as Sensu Go doesn't employ JSON object "merging" as a core function for compiling the configuration of the overall system. This was previously handled by [the `deep_merge` function in the sensu/sensu project](https://github.com/sensu/sensu/blob/master/lib/sensu/utilities.rb#L34-L53)._ 🤓 

@majormoses – I would normally say "let me know if I missed anything", but I'm intentionally leaving out certain details for brevity (he says at the end of a 500+ word GitHub comment 😆 ). Any additional feedback you can share on what does and doesn't work for your team in the fatigue-check-filter would be great. We're probably overdue to offer a supported version of that filter or something like it under the github.com/sensu org, so your feedback will be very helpful in identifying what the right next steps are. 

Cheers! :beers:

**Comment by calebhailey** [comment]
@nixwiz let's follow-up on our discussion from earlier today RE: moving the fatigue-check filter to the Sensu GitHub org sometime next week. 

@majormoses I'm going to go ahead and close this issue as there's no change needed in sensu/sensu-go, but please feel free to re-open it if you have any further questions. 

Cheers 🍻
