### ISSUE TITLE
Dashboard terminology unclear w/ mix of search states and event states

### ISSUE THREAD

**Issue by agoddard** [sensu/sensu-go#4239]
## Feature Suggestion
Icons and terms in searches refer to what appears to be the same things (but is not, when studied closer) with different names, such as "non-passing" which looks like "unknown" and "flapping" which looks like "warning"

It would be ace to see if we can disambiguate these further, or reintroduce more common terminology. The current behavior has lead to users interpreting the change as a change away from our standard check terminology of "ok" "warning" "critical" "unkown" etc

Sensu internal ref: https://secure.helpscout.net/conversation/1465225819/25080?folderId=1211658

**Comment by hurrycaine** [comment]
I wanted to add it is not just a question of semantics.  
Right now there is no filter, to filter out Warning and Unknown events. Not passing and Critical return the same results. To concentrate on critical events.

Not passing and Failing return the same results. 
![event_notPassing](https://user-images.githubusercontent.com/7150930/112629599-6f2f2d00-8e2c-11eb-9a37-1b0d5935271d.JPG)

![event_failing](https://user-images.githubusercontent.com/7150930/112629645-781ffe80-8e2c-11eb-97f8-b9197a76fdfe.JPG)

Passing works and I don't have anything to test flapping with.

Also, On the entity page it shows the entity as critical even if the event is a warning. (not sure about unknown)

**Comment by calebhailey** [comment]
Sensu Go 6.4.0 added support for distinct "status" filters (i.e. filtering on the `event.check.status` field, with values like 0, 1, 2) and "state" filters (i.e. filtering on the `event.check.state` field, with values like "passing", "failing", "flapping"). 

![screencast](https://user-images.githubusercontent.com/141373/134574958-a35c2511-383d-4c39-91ac-1e021e8d36b1.mov)

The event list "Status" filter drop-down no longer applies an `event.check.state` filter as was the case at the time this issue was filed. The event filter actions now match the button label. The filter labeled "Status" now applies an `event.check.status` filter, and the filter labeled "State" now applies an `event.check.state` filter.
