### ISSUE TITLE
Check stop execution when secret provider is not reachable

### ISSUE THREAD

**Issue by guipe** [sensu/sensu-go#4261]
## Expected Behavior
When secret provider (Vault) is not reachable, all checks which use this provider must continue to be executed, and these check must pass to critical status.

## Current Behavior
When secret provider (Vault) is not reachable, all checks which use this provider stop execution, and these checks left in OK state.

## Steps to Reproduce (for bugs)

1. Stop communication between Sensu-go backend and Vault
2. Verify checks which use secret from Vault (checks are not more executed and their status is always OK)

## Context

When Vault is not reachable, all checks which use secret stay in OK status. 

These checks must fail as secret are not more reachable.

## Your Environment

* Sensu version used (sensuctl, sensu-backend, and/or sensu-agent):sensuctl: 6.0.0 sensu-agent:6.1.2 sensu-backend: 6.2.5
* Installation method (packages, binaries, docker etc.): docker
* Operating System and version (e.g. Ubuntu 14.04): CentOS 7.8.2003

**Comment by portertech** [comment]
This needs further discussion. How should Sensu really surface backend errors/issues?

**Comment by calebhailey** [comment]
Let's schedule a Tuesday engineering discussion for this one to review outstanding proposals.

**Comment by calebhailey** [comment]
Updates: 

* As a first step, we think we can improve the UX here by implementing #4442 and #4443, and generating a normal Sensu Event when a backend is unable to retrieve a secret (this also opens the door for exposing other scheduler & event processing events as Sensu Events)
* We are still hesitant to modify the scheduler behavior to allow checks to be scheduled when a secret it depends on is unavailable, so we will not be modifying this behavior at this time 
* We will continue to explore a solution for updating Events to indicate various configuration issues (e.g. unavailable secret and/or unretrievable asset) instead of the current behavior which may result in potentially misleading "stale" OK events

**Comment by calebhailey** [comment]
We'll probably need to create the following issues in https://github.com/sensu/sensu-go and https://github.com/sensu/sensu-enterprise-go: 

- [ ] [sensu/sensu-go] Add a GenerateSensuEvent() or GenerateSensuBackendEvent() function to sensu-backend
- [ ] [sensu/sensu-enterprise-go] Generate a Sensu Event when a backend is unable to retrieve a secret from a SecretProvider (w/ `namespace:<system-namespace>` & `entity:<sensu-backend-id>`)

TBD if exceptions we handle as backend events should _also_ be reported as an error to the Sensu log (because the event itself would be logged by Sensu)??
