### ISSUE TITLE
Backends create sensu-system namespace and its entity

### ISSUE THREAD

**Issue by calebhailey** [sensu/sensu-go#4443]
## Feature Suggestion

Sensu backend entities should be visible in the Sensu API and web app. 

## Possible Implementation

On backend start:

- Check for `sensu-system` namespace
** Create if missing
- Check for existing entity in the `sensu-system` named after the backend's local hostname
** If missing, create a new entity with `entity_class` of `backend` and populate the entity system information
** If one exists, don't touch it

Backend uses its own entity when reporting cluster state errors.

## Context

See: #4442

**Comment by fguimond** [comment]
A new backend entity should be created by all backends running in a Sensu cluster. The backend entity should be marked as such and operations on it should be limited. A user should not be allowed to delete it. Update operations should also be limited. 

# CRUD

## Create
When the backend starts up a new entity should be automatically created. 
* Name: use the same algorithm the agent uses to determine the entity name
* Namespace: the system namespace - `sensu-system`
* EntityClass: backend

We should not allow the manual creation of backend entities.

If both a backend and an agent try to create the same entity the entity class should default to `backend`. The information provided by the backend should have precedence over the information provided by the agent. If somehow the entity is first created by the agent the backend should update the entity information.

## Update

Only the labels and subscriptions should be editable, and only by users having proper write privileges for the `sensu-system` namespace.

## Delete

See [Deregistration and Disposal section](#deregistration-and-disposal) below.

# Behavior

* Events generated by a sensu-agent running on the backend host should be associated to the backend entity.
* Events should be generated by the backend on error conditions such as unavailable components.

## Keep-Alive

Since there is no guarantee a sensu-agent will be running alongside the backend I believe the backend should generate periodic keep-alive events.

**Question**: What should the behaviour be when there are both a backend and an agent generating keep-alive events?

## Deregistration and Disposal

There are two ways of disposing of old backend entities. The first one is to support deregistration for those entities. The backend entity would then be deleted when it has not been seen for a period of time.

**Question**: What should be that period of time?

The second way of deleting a backend entity is to allow properly privileged users to do it manually. In this case however safeguards should be in place to prevent a user from deleting a backend entity if it is still being used actively.

## Periodic Events

This doesn't need to be part of MVP but periodic events can be automatically generated by the backend. Health and metrics come to mind.

# User Interface

## Sensuctl

The `sensuctl entity list` should display `backend` as the entity class. 

The `sensuctl entity info <entity>` command should also display `backend` as the entity class.

Editing a backend entity using `sensuctl edit` should prevent updating critical fields:
* name
* namespace
* entity_class

**Comment by portertech** [comment]
Updated issue description with new limited feature scope. We intend to implement the most basic version first and then enhance it's capabilities over time with user feedback (i.e. backend entity life-cycle management).

**Comment by calebhailey** [comment]
We _may_ also want to add a `system:user` Role+RoleBinding with the following (for new clusters only?): 

```
---
type: Role
api_version: core/v2
metadata:
  name: sensu-system
spec:
  rules:
    - resources: 
      - "*"
      verbs:
      - get
      - list
      resource_names: []

---
type: RoleBinding
api_version: core/v2 
metadata:
  name: sensu-system
  namespace: sensu-system
spec:
  role_ref:
    name: sensu-system
    type: Role
  subjects:
  - name: system:user
    type: Group
```

**Comment by calebhailey** [comment]
🙌
