### ISSUE TITLE
[UX] : Missing resources in Pipeline should throw warning or any indication in UI/sensuctl/API call

### ISSUE THREAD

**Issue by aaggarwal-sumo** [sensu/sensu-go#4648]
[UX] : Missing resources in Pipeline should throw warning or any indication in UI/sensuctl/API call

## Expected Behavior
Some warning in UI or STDOUT using Sensuctl or Response body in API call

## Current Behavior
Missing resource doesn't give any indication in UI or STDOUT or in Response body

## Possible Solution
Add Some warning in UI or STDOUT using Sensuctl or Response body in API call

## Steps to Reproduce (for bugs)
Create some Check and define Handler which doesn't exists.

## Your Environment
Sensuctl installed using docker package.
Sensu-agent installed on mac laptop with docker package.
Sensu-backend installed with docker image.

**Comment by aaggarwal-sumo** [comment]
@portertech  Please let me know if anything is required.

**Comment by echlebek** [comment]
While this would be convenient at the time of creating resources, sensu is designed to be tolerant of missing information, so that resources don't have to be created in a particular order. This late-binding of configuration is by design and we can't do this without breaking other fundamental properties of the system.
