### ISSUE TITLE
[Spike] Design EntityConfig Store for Postgres

### ISSUE THREAD

**Issue by c-kruse** [sensu/sensu-go#4719]
## Design Postgres Backed EntityConfig store

Per the discussion on this document on 5/2: https://docs.google.com/document/d/1OfT6fLIqKggGt0pKcFiBGa6Jb5KgygX7DpSy9Pt0XSo/edit?usp=sharing

**Notes from meeting:**
* EntityConfig has a unique access pattern that is not suitable for our general configuration store approach.
* It is written to more regularly than typical configuration resources and is frequently read in conjunction with EntityState, implying we may want some relation there.

**Comment by amdprophet** [comment]
A general configuration store approach is immediately less performant than a separate table for entity configuration due to less columns being required to identify a row. For 1,000,000 rows the performance difference was roughly 13%. Furthermore, a general configuration table may not be an optimal choice for instances where foreign keys are required for relational data (e.g. entity config & entity state).

We should move forward with keeping entity configuration in a separate table.
