### ISSUE TITLE
packagecloud reports 402 Payment required

### ISSUE THREAD

**Issue by pstadt** [sensu/sensu-go#5056]
Downloading from https://sensu.io/downloads for redhat and debian reports http status **402 Payment Required**: 
https://packagecloud.io/sensu/stable/packages/ubuntu/focal/sensu-go-cli_6.11.0-7218_amd64.deb/download.deb

Are there any alternative sources for the linux packages?

**Comment by alexhogbergepiceros** [comment]
Same here, not aware of any alternative sources.

**Comment by jedi-marcus** [comment]
Same for Ubuntu. I wonder if it's not more a packagecloud.io issue (who were acquired in Sep '23) or a sensu issue. I'm pretty sure the repo still worked last week

**Comment by JonEllis** [comment]
From my records it was working March 15th 06:00 UTC, then failing with the 402 Payment Required error on March 16th.

I haven't seen any documentation changes with Sensu to indicate it's intentional, so I'm hoping that they've merely let a payment to PackageCloud lapse.

If I'm correct with this assumption and if Sensu is still maintained (🤞) then I expect they'll fix it by paying their bill, or moving the repo elsewhere.

**Comment by ping-localhost** [comment]
> I haven't seen any documentation changes with Sensu to indicate it's intentional, so I'm hoping that they've merely let a payment to PackageCloud lapse.

Reading https://github.com/actions/runner-images/issues/1983#issuecomment-870836355 this sounds correct.

**Comment by jedi-marcus** [comment]
On another note... Sensu doesn't really seem active no?
no commits in 8 months, no releases, discourse is pretty dead, I see Caleb H. has left the company...

**Comment by ping-localhost** [comment]
https://packagecloud.io/sensu/stable/gpgkey and the DEB downloads seem to work again. 👌

**Comment by pstadt** [comment]
I can confirm, problem is gone.
Package download works again.

**Comment by sensu-discourse** [comment]
This issue has been mentioned on **Sensu Community**. There might be relevant details there:

https://discourse.sensu.io/t/is-sensu-go-still-alive/3198/2
