### ISSUE TITLE
Hook assets

### ISSUE THREAD

**Issue by grepory** [sensu/sensu-go#929]
As a user, I want to be able to use assets for check hooks.

**Comment by craigpfeiffer** [comment]
as a work around to check hooks not having direct asset configuration i did some testing to see if a check hook has the same $PATH as the check that is triggering the hook.  unfortunately it does not appear as a viable solution either.

created a check with an asset and attempted to run the script within the asset in the hook and it failed with a command not found error.  also updated the hook to output the $PATH as well as the check to output the $PATH to compare them.

check $PATH:
`output": "/var/cache/sensu/sensu-agent/eca51a0f4c9ad1d520d24025b0579dea9a56899a668475f8a0f4c319b40e2578278cd3109d2846a1ce1dccd09f27a1fd7c08ef7eef5897d1741ab070099d5446/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin\n",`

check hook $PATH:
`"output": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin\n",`

**Comment by annaplotkin** [comment]
This has come up as a higher priority due to a use case from teams at NCR. 

In the event that a service encounters an issue, the teams tail the logs. Sometimes the logs are quite large and it would be beneficial for them to be able to leverage hooks for powershell assets to achieve this rather than writing dubious checks. Raising higher in the Backlog.
